label Event_Party01:
    scene nocturnaltrunk
    hide screen menu_buttons
    "Surprise!"
    $ renpy.music.play(mParty, loop=True, fadeout=1.0, fadein=1.0, if_changed=True)
    show ole normal at r2
    show ole normal at r1 with move
    "Many familiar faces jump out at you."
    "Basically everyone you have met in Lusterfield is here."
    "Food lines the tables, and drinks are flowing freely."
    "You don't know what is happening. But at least everyone is in a jovial mood."
    show ole grin
    o "[e]! Welcome! We figured it'd be a surprise for you."
    show haskell normal at l2
    show haskell normal at l1 with move
    "You see Ole nudge his elbow into Haskell's side."
    h "mhmm...! You almost made me choke-... uh... Good to see you here, [e]."
    e "Haskell, you're here too?"
    "You see Haskell continue to sip his tea."
    show haskell normal at l2 with move
    show amble normal at l2
    show amble normal at l1 with move
    a "[e]! The Tavern is getting so crowded! Everyone's here."
    show lothar normal
    with dissolve
    l "Well, he's my disciple after all. [e], I'll let you get the spotlight just this once."
    e "T-thank you, Lothar, I'm glad you're here."
    show lothar normal at r2 with move
    "You notice Rahim standing to the side, waving at you."
    hide amble normal with dissolve
    e "Rahim?"
    r "...Just here to see how the tavern is doing. But, the party is well deserved."
    "Seb hops over."
    show sebas normal at l2
    show sebas normal at l1 with move
    s "Roomie! You're finally here!"
    e "Seb, wh-what's all this?"
    s "It's a party! Duh!"
    e "Party? What's the occasion?"
    s "It's to celebrate you being a part of Lusterfield!"
    e "Th-that's..."
    "You are gobsmacked. You have never had a party thrown in your honor before. You feel touched."
    "Then, you frown."
    e "Wait. So there's no training after all?"
    s "Yea. That was just a distraction to send you away so that we could get things prepared. I was shocked that you fell for it, Roomie!"
    "Seb guffaws as he smacks your back."
    s "Anyway, Roomie, I won't hog anymore of your time. You should go to talk to everyone! This is your party after all."
    s "But before we go, remember to come back and talk to your Roomie, that's me!"
    show sebas normal at r2 with move
    "You look around the tavern, and the people you have come to know as friends and mentors nod and smile at you."
    "Everyone is enjoying the festivities... Some more than others."
    "The tavern has been cleaned in preparation, and the normal patrons are nowhere to be seen."
    "You believe this celebration is invite-only."
    "You see Cane working the counter as usual. He is pouring out the drinks."
    show cane normal with dissolve
    "You walk over to talk to the barkeep."
    c "Today is a special day so I'm not going to get ya to work."
    c "So go mingle around. There's no reason to stick around here with an old bat."
    e "Cane, thank you."
    c "Whatcha thanking me for?"
    e "Well, this is your tavern, right? The food and the drinks must be expensive too."
    c "Ye well. I'd never say no to gold."
    "You are shocked."
    e "Wait. Someone paid for this? Who?"
    "Cane looks at you and chuckles."
    c "I was only pulling yer chain. Nah, this time, everything's on the house."
    e "Huh? You paid for this?"
    "You cannot help but narrow your eyes. Cane is not known for his generosity with gold. You wonder if there's another angle behind this."
    "Suddenly, you feel a pinch on your ass."
    c "Okay. Now, get lost with the others. Yer distracting me with yer squeezy little ass."
    e "...Fine. But I'm keeping my eyes on you."
    c "For what?"
    e "...see if someone sneaked you some gold under the pocket."
    "You quickly wiggle away from the counter."
    hide cane normal
    show rahim normal
    with dissolve
    "You glance back at the side, and see a massive figure occupying the corner booth by himself."
    "The air of festivity appears to stop right before touching him."
    "You are honestly surprised to see Rahim here considering his history with Cane."
    "However, Rahim does seem visibly uncomfortable."
    "You walk over and Rahim appears to relax slightly."
    e "How's everything, Rahim?"
    r "Could be better."
    e "I can't believe you're here."
    r "Me neither."
    "Rahim sighs and seems to take in the surroundings for the first time."
    r "It's been quite some time since I was last here."
    r "Many things have changed, but not enough."
    "It's not hard to imagine him thinking about Cane's previous server."
    "You try to lighten the mood."
    e "Anyway, I'm thankful that you're here."
    "Rahim grunts and shrugs."
    r "Like I said, only here for the drinks."
    "As if to prove his point, Rahim downs the large mug of beer."
    r "You don't need to check in on me... But nice chat..."
    r "Now, let me drink in peace."
    e "Alright. Enjoy the party, Rahim!"
    "As you leave, you notice the heaviness around Rahim lift slightly."
    hide rahim normal
    show ole normal
    with dissolve
    "At that moment, Ole saunters over and greets you."
    o "You're finally here. I was worried that the courier training would have taken you days to complete."
    "Ole chuckles at the joke."
    o "Okay, maybe that's too on the nose. Anyways, sorry for making you go on a wild goose chase."
    o "Seb was supposed to be the one to keep you distracted, but I had a feeling he'd fail at it."
    "You think back to the many times Seb fumbled over his words this morning."
    e "You weren't wrong."
    "Ole shares a smile with you."
    e "By the way, how did this come into being?"
    o "It was all Seb's idea. He wants to have a celebration to mark your integration into Lusterfield."
    o "He's been planning it since the first day you came..."
    o "He talked to me about it, and I thought it was a good idea, so I helped."
    e "You mean, you handled the whole thing?"
    e "Like, I'm seriously doubtful that planning and Seb can go together."
    "Ole laughs."
    o "You undersell Sebas. Plus, it's the intention that matters. All of us came together to make this happen."
    o "So enjoy the party. You've earned it."
    "Ole pats your arm and walks away to greet another guest."
    "Suddenly, the ground beneath you trembles slightly."
    "You turn and see a giant stomping your way."
    hide ole normal
    show amble normal
    with dissolve
    a "Coming through!"
    "Amble is carrying many mugs in his hands. You wonder how he manages to balance them all."
    "As you move out of the way, Amble catches you and grins brightly at you."
    a "Hey, it's the dragon of the hour!"
    "Amble stops to chat with you. Surprisingly enough, all of the drinks in his arms halt. Not one drop is spilt."
    a "Great party, isn't it? And the drinks are on the house, too!"
    a "This is one of the happiest days of my life and it's all thanks to you!"
    e "Amble, you exaggerate!"
    a "No. Really. You've brought a lot of positive changes to Lusterfield."
    a "Jog and I have more to talk about, and he doesn't seem as tense as he was before."
    a "Lot is also smiling a... lot more these days."
    "You are blushing from all the compliments at this point."
    a "Great job!"
    "While you wish to continue the conversation, Jog's voice calls over."
    j "Amble, we're dying of thirst here!"
    a "Gotta go. Talk to you later, pal!"
    "Amble trundles away to his friends."
    hide amble normal
    show haskell normal
    with dissolve
    "You feel a sharp gaze on you all of a sudden."
    "You look around and eventually spy the source."
    "Haskell is sitting alone at a table, gazing at you over a familiar cup."
    "You feel like you owe him a talk since he has traveled the furthest to this party."
    h "This place sure is rowdy. I still prefer the quiet of the hut."
    h "Granted, there is still the occasional buggbear. Luckily, I can take them out with some sedative pretty easily."
    h "I doubt I can do that here."
    "You are not sure if the dragon is being serious or not."
    e "Please don't do that."
    "Haskell doesn't answer and takes another sip from his mug."
    "Speaking of, you are curious about one thing."
    e "Haskell, now that we're in a tavern, are you drinking alcohol?"
    "Haskell snorts at the very idea."
    "Haskell tips his mug to show you its contents."
    "It's tea as usual."
    h "Nothing is better than tea. If I really want a buzz, there's a concoction back home that I can cook up that's much stronger than the drinks here."
    h "Perhaps one day I'll have you try some."
    "You are not sure if that's a good idea. You change the subject."
    e "Since you're here, why not get to know people? The folks at Lusterfield are nice."
    h "I prefer my own company. Too lazy to converse."
    e "You're talking to me."
    "Haskell looks at you, takes a long drag from his mug and silence ensues...."
    hide haskell normal
    "Point taken."
    "As you move around the tavern, suddenly, somebody knocks into you."
    show lothar normal
    with dissolve
    "You balance yourself on a table and right yourself."
    "Looking up now that you're settled, you see a shadow swaying before you."
    "Eventually, the shadow settles into the form of Lothar."
    l "Hey, who doesn't have eyes to have bumped into the hero of Lusterfield?"
    "You can see that Lothar's face is flushed from inebriation."
    "As you are about to apologize, Lothar's eyes focus."
    l "Oh! It's my Disciple! Good... Party you got there."
    l "Hu...hmm... Can you stop moving?"
    "You are standing perfectly still. It is Lothar who is swaying on his unsteady feet."
    e "Lothar, you're drunk. You better sit down and rest."
    l "Nonsense! The hero is never drunk! This is nothing for me."
    l "In fact, I can down another 100 mugs of beer!"
    "You move to help steady Lothar."
    l "I'm fine, Disciple! Don't underestimate the Hero."
    l "I just need to clear my mind for a moment, and I'll be back for more."
    "Before you can stop him, Lothar shuffles away, teetering on his feet."
    "You hope that he won't bump into anything dangerous, like Seb."
    "That would be an incendiary scene."
    hide lothar normal
    "You look around the tavern and notice that a person is missing."
    "However, you know that he has to be here because his friends are here, and because you heard him ask for beer earlier, so you look closer."
    "Finally, you spot a fleeting shadow near the back of the tavern, where the boxes are stacked."
    "You move towards it."
    show jog normal
    with dissolve
    j "Well. Fancy seeing you here."
    "Jog leans against a box casually, holding a mug in his hand."
    e "Why aren't you out there with the crowd?"
    e "I was expecting you out there..."
    j "Where did you think I got this drink from?"
    "Jog tips back the whole mug."
    "His face isn't flushed at all. It is as if the alcohol has no effect on him."
    e "You sure know how to handle your liquor."
    j "Why, thank you for the compliment."
    j "A scout has to stay vigilant at all times. Plus, someone has to be clear-headed to take care of Lot and the blockhead."
    e "That's very thoughtful of you."
    "This time, there's some redness on Jog's cheeks."
    j "Eh. Someone has to do it."
    j "Anyway, this has been fun. I'll have to go grab another beer. It's not everyday that I can swipe one from the counter without the barkeep glaring at me."
    "With that, Jog slips away into the shadows."
    hide jog normal
    with dissolve
    "Suddenly, you feel someone hug you from behind."
    "It's very warm."
    show sebas normal
    with dissolve
    s "Roomie! I've finally caught you!"
    e "I'm not going anywhere."
    s "You were so busy talking to others that I thought I'd come to you instead."
    s "Surprise!"
    "Seb chuckles. His fur tickles you."
    "Seb lets you go and grins at you."
    e "Seb, thanks for throwing this party for me."
    s "Roomie, you deserve it. After everything you've done for Lusterfield, this is the least we can do!"
    s "Plus, you've done a lot for me too."
    s "With you around, the time I spend working at the shop is not as boring."
    s "Plus, I get to hear stories of your adventures too!"
    s "And you're the only person to appreciate the shop sign that I've made."
    s "You've done so much for me and everyone else!"
    s "Roomie, you're the best!"
    e "Seb, you're the best too!"
    e "If you didn't rescue me back at the forest, I wouldn't have met so many amazing people."
    s "Aww, Roomie. You're going to make me blush."
    s "But enough of the sappy stuff. Today we're here to celebrate. Go grab some drinks!"
    "And the party ensues."
    hide sebas normal
    with dissolve
    "As the party continues, people break up and form different groups."
    "It's rare for people to have a chance to gather like this."
    "Some are taking this chance to get to know new friends, others to solve old rivalries."

    menu:
        "Where do you want to visit?"
        "Listen in on Sebas and Lothar's table":
            $ sebaslothar += 1
            "You hear an argument coming from somewhere in the tavern."
            "Lothar and Sebas are arguing. Haskell remains seated at his table, sipping his tea."
            show sebas bored at l1 with dissolve
            show lothar angry at r1 with dissolve
            s "How drunk must you get that you can't even watch your step anymore?"
            l "Shut it, lion! I'm not even drunk! Stop finding excuses to fight with me."
            "A low growl rumbles from Seb's throat."
            "Lothar's face is still red but it's no longer due to alcohol, but anger."
            "You hurry over to mediate before a fight breaks out."
            s "Why are you even here?"
            l "Do you think I want to be here? I'm not even here for you."
            s "Then leave! And take your lackeys with you."
            l "Hey, lion! Watch it! It's one thing to come after me but it's another to insult my mates."
            s "Did I get anything wrong? I can't say I'm surprised. Criminals stick together."
            l "You take that back!"
            s "Make me."
            "Lothar's coat bristles with tension."
            "Seb also moves in place to counter."
            "As you are about to burst through to the center to stop them, there is a heavy slam on the table."
            "It stops both Lothar and Sebas."
            "All of you turn to the source."
            "Haskell has slammed his mug on the table and there's a dangerous glint in his eyes."
            show haskell normal with dissolve
            "Then, he breaks into a smile that doesn't quite reach his eyes."
            h "Boys, why don't we calm down? How about some tea to ease the hot blood?"
            h "All this chaos is making it difficult for me to enjoy my tea in peace."
            h "Plus, are you sure you want to do this with the guest of honor standing right there?"
            "Haskell points at you."
            "Lothar and Sebas turn to look at you. Both of them immediately flush red with shame."
            "They put away their aggression immediately."
            s "He... he's right. This is a party."
            s "I'm sorry about that, [e]."
            "Before you can say anything, Seb turns and walks away."
            hide sebas normal with dissolve
            "At the same time, Lother grumbles under his breath."
            l "You got lucky this time, Lion."
            "Lothar glares at Haskell and then at you before stalking away."
            hide lothar normal with dissolve
            "You are quite flustered. You have no idea what to do and who to chase after."
            "Unexpectedly, Haskell speaks again."
            h "Hold your horses, young courier."
            h "Take this old dragon's advice. Give them some time to chill. You going to them now will only reignite the fire."
            e "They're really angry... I-I don't know what to do."
            h "Certain things are easier to handle when one's mind is not clouded by anger. This is not the occasion to strike while the fire is hot."
            h "..."
            h "This is why I hate social functions."
            "Haskell resumes sipping his tea."
            "You ponder over his advice and agree, deciding to give both parties some time to cool down."
        "Listen to Ole and Jog at the corner":

            $ olejog += 1
            "You notice Ole and Jog seated at a secluded corner of the tavern, away from prying eyes."
            "You do not interrupt them for they seem like they need privacy."
            "As you start to walk away, their conversation drifts over and into your ears."
            show ole normal with dissolve

            o "It has been a long time... since we could talk like this."
            show jog normal at r1 with dissolve
            j "You're right about that."
            "The usual cheekiness in Jog's voice is gone. It is rife with shame."
            "You know it is wrong but you can't help but stop moving. You want to know more."
            o "How have you been?"
            j "Not bad. Hanging out with Boss and Amble is fun. What about you?"
            o "It's the usual back at the shop. But we have a new roommate living with us there."
            j "Yes, the new courier. That one's some nice eye-candy."
            "There is a temporary silence."
            j "Oh. Don't tell me you haven't noticed?"
            o "Jog, you still haven't changed, have you?"
            j "Why should I? There's only one person who wants me to change anyway."
            j "Speaking of, how's your lion friend?"
            o "Jog, this is a happy occasion. Do you have to bring that up?"
            "Ole sighs."
            j "It's rather hard to do that when your friend has been giving me the evil eye all night."
            o "Don't say that. Plus, he is your friend too."
            j "No. Was. The friendship was over once he accused me."
            o "You didn't give him much choice."
            j "Now, what does that mean?"
            o "You know..."
            "Jog's voice hikes up a bit."
            j "No, I don't."
            o "If you hadn't swiped the merchandise from the counter, Seb wouldn..."
            j "I'm going to stop you right there."
            j "I did no such thing. Yes, I have a sketchy background but I would never steal from my friends."
            o "But the evidence..."
            j "I told you they're false. Also... Ole... I haven't really heard from you. Do you believe me? Did you think I did it?"
            o "I..."
            "Ole sputters."
            j "This is unbelievable."
            "Jog sounds frustrated. He sounds like he's about to storm off."
            "At that moment, Amble lumbers over."
            show amble normal at l1 with dissolve
            a "Hey friends! Jog, where are you going? I just got us a brand new round."
            "Amble pushes Jog back down into his seat, and places the mugs of beer on the table."
            a "Hey Ole! Great party, isn't it?"
            a "Here, a beer for you too!"
            "Amble stumbles into the awkward situation with a charming insensitivity that only he can manage."
            "Then, Amble leans over to Ole and whispers in a voice that is no quieter than normal."
            a "Also, is there something wrong with your lion friend's eyes?"
            a "He has been giving us a look out of the corner of his eyes all night. Perhaps he needs to get them checked? I'm worried about him."
            "Ole doesn't quite know how to respond, and Jog cuts in."
            j "Amb, you've probably just been imagining it. I didn't notice anything like that."
            "Amble scratches his head innocently."
            a "Really? Perhaps you're right then."
            a "But no matter. The important thing is that we're with friends."
            "Amble raises his mug to cheer Jog and Ole."
            "You decide to leave the three alone."
        "Check in between Cane and Rahim":
            $ canerahim += 1
            "As the party dies down a bit, Cane has some time to relax."
            "You see him leave the counter and take the seat across from Rahim."
            "Instantly, the tension in the air is palpable."
            "You don't interfere for you know they have something to work out."
            show cane normal at r1 with dissolve
            c "Thanks for coming over."
            "You notice Cane dropped his usual accent... around Rahim."
            show rahim normal at l1 with dissolve
            r "Didn't do it for you."
            c "Regardless, it means a lot."
            "For once, Cane sounds sincere."
            r "Hmm."
            c "Look. I'm sorry about what happened to Topu."
            "Rahim's grip on the mug tightens."
            c "I didn't know the kid would act so recklessly."
            "Rahim still doesn't say anything."
            c "I care about the kid as much as you do."
            "Rahim snorts."
            r "If that were true, he'd still be here."
            "Cane chokes on his words and looks down in silence and guilt."
            "After a while, Cane resumes speaking."
            c "For what it's worth.... I'm sorry."
            "Rahim pauses and then takes another sip of beer."
            r "You owe him an apology, not me."
            "Then, there is a stretch of silence."
            r "...Your beer still tastes like shit."
            "Cane cracks a small smile."
            c "People like the swill."
            c "Speaking of, I better get back to work."
            "Before he leaves, you notice Cane turns back to Rahim."
            c "I mean it, it's good to see you here."
    hide cane
    hide haskell
    hide amble
    hide ole
    hide jog
    hide rahim
    "You leave the groups to their own business..."
    "You look at your friends scattered around the tavern. People that wouldn't have interacted are now gathered under one room."
    "Haskell and Amble are conversing about the different properties of tea."
    "You swear you can see stars on Amble's head. Most of the details must have flown over him but he's too polite to leave the conversation."
    "Jog crosses path with Seb. Jog slithers away but not out of fear but more like a refusal to engage in meaningless argument."
    "Seb merely glared at Jog as the latter moves away. You have never seen your roommate act like this before."
    "Rahim is trying to fend off a persistent Lothar who is aiming to finagle a new armor from Rahim."
    "Rahim's refusal is firm and affirmative. That doesn't quite faze the Hero of Lusterfield even though he does appear more cowed around Rahim."
    "Ole and Cane are chatting over the counter. You believe Ole is trying to negotiate a business deal to have Cane sell some of his food and drinks at the shop."
    "Even during this occasion, Ole is trying to help out Seb. You hope they can reach a consensus that is beneficial to both parties."
    "It seems the party is still going strong..."
    "Soon, Jog and Lothar went over to Cane for beer."
    "Amble is joining in with Sebas, Rahim and Ole on the other table."
    "And Haskell... seems to be looking over at the exit."
    menu:
        "Where do you want to visit?"
        "Drink beer with Jog, Lothar and Cane":
            show lothar normal with dissolve
            l "That lion... he's... never going to learn isn't he..."
            show jog normal at l1 with dissolve
            j "I know..."
            show cane normal at r1 with dissolve
            "You walk towards the three across the bar, and join in with the group."
            j "I know..."
            c "Cut him some slack, ya dink donks."
            c "Hey, good to see you, my lad. Take a seat."
            e "H-hey! What are you talking about?"
            l "Your 'Roommate', I suspect he's got some problems in the head."
            l "I just don't understand why someone would be so obsessed about fucking over Jog like that."
            e "Uh...?"
            l "I gave him a fair punishment after that, and now? he's obsessed with kicking my balls."
            c "Maybe if ya didn't do it to him in the first place."
            c "[e], a beer?"
            e "Y-yes please."
            l "You're living with him, disciple."
            l "Be careful when you sleep, you'll find the lion staring at you in the middle of the night."
            j "Lot..."
            c "Here's your beer, [e]."
            c "And ya two, change the subject."
            l "What?"
            c "Ya wanna keep bumming out my lad at his own party?"
            l "..."
            j "I've got a good one, I was walking down the road last week, and I found that elk."
            l "W-who?"
            j "The elk. He's near the werewolves' den."
            c "Huh?"
            c "Where did ya find him?"
            j "I just told you, Cane. How about you, have you seen the elk?"
            e "Hmm, no."
            j "Sad. He's got such a fat cock hanging down there."
            e "...what?"
            l "Ok, your time's up, change the subject."
            j "H-hey I've not finished yet."
            l "Spotlight's yours, disciple. What's with you and that friend you were talking about?"
            e "Huh?"
            l "I forgot his name."
            c "Chime?"
            c "I got it from the lion."
            e "He... I don't know. I have no idea where he went."
            j "He's up the mountain, no?"
            e "I... I hope so."
            e "To be honest, I'm really grateful for all of you around here. It wasn't always like this in my own tribe."
            e "...Only Chime was there for me then."
            e "I'm not even sure if I want to go back if I get the chance to."
            c "Lad..."
            "You can feel Cane struggling with his words. Almost as if he has been through something similar once already."
            j "You can stay as long as you want."
            l "What's wrong with your tribe and all anyway. I, as a hero, have never seen something like this."
            l "I don't even know where you're from."
            l "Lizard says you're from another world."
            l "But... what if you're just from somewhere far far away...?"
            e "I don't know. The trees... they look so similar to the ones I saw when I met that monster."
            j "Ah, what if you just fell into a deep slumber for a long time. Like, say a hundred centuries."
            l "That doesn't even make sense, Jog."
            c "I suggest ya go check on that monster of yers. We have no idea where yer sleazy ass came from."
            j "By the way, everything's been freaking out since you and your friend came along."
            j "The goats and their stolen runes, and the bears... I heard from Amble that they started acting weird around the same time as well."
            l "The goats got what they had coming to them."
            l "Disciple, now that I look at you, you do look like a goat."
            e "Uhh? What?"
            l "The horns and stuff. Must be a different world thing."
            c "Nah, this lad's more like a dragon. Didn't that potion maker have fur also."
            j "I would still expect some scales on a proper dragon."
            "You feel a little awkward letting the three to discuss your look. So you decide to withdraw yourself from the table."
            e "...I think I should go, I've drank enough beer."
            c "H-hey! Lad... something wrong?"
            e "N-no... just don't want to get too drunk."
        "Sit with Amble, Rahim, Sebas and Ole":
            "You walk towards the table and notices Amble standing there as well."
            show amble normal at r1 with dissolve
            a "Hey...I'm getting tired, mind if I join you three?"
            show sebas normal with dissolve
            s "Sure Amb, Rahim vouched for you."
            a "Ha- Thanks."
            show ole normal at l1 with dissolve
            o "Hey! [e], come and take a seat!"
            e "Oh..."
            o "We're just chatting."
            e "Thank you for throwing me a party by the way."
            s "No, thanks for being here with us."
            s "You've been a good roomie all along!"
            a "..."
            a "Hey... Seb, what's wrong with your ey-"
            "You notice Ole elbow Amble in the ribs."
            a "Ah... what?"
            show sebas normal at l2 with move
            o "Ehem! So, [e], how's the party?"
            e "Uh... good? I'm just glad we're all coming together today."
            o "I agree, we should all come together more often."
            o "Anyways, Seb and Rahim were playing chess upstairs the other day."
            o "Maybe you should join in some time?"
            e "What's chess?"
            o "You've got some pawns, a king, a queen, a-"
            a "A pawn and a king? So that's where the name of your shop came from."
            o "Yes, Seb liked to start the game with the pawn in front of his king."
            o "And Rahim starts with the queen's pawn."
            show rahim normal with dissolve
            r "Look, theoretically queen's pawn gets you more advantages as white."
            hide ole normal with dissolve
            show sebas normal at l1 with dissolve
            s "No, not in practice, Rahim. I've won twice as often as you."
            r "Ugh... That's because you always cheat with your weird rules about the pawn."
            s "That's en passant."
            e "I don't understand a single word..."
            s "Buddy, you'll understand when I teach you about the amazing world of chess."
            a "Can I learn too?"
            s "Amb, you sure you don't want to join Lothar instead?"
            a "They're all talking about their own stuff today. Plus I've never seen chess before."
            a "Sounds like something straight from the town."
            s "Fine, you can join as well."
            a "Great."
            "You see Sebas stop giving Amble the evil eye. He still continues giving it to Lothar and Jog."
            e "I think I should go now."
            e "Just to see how the others are doing."
            s "Oh take care! [e]."
            "You politely stand up from your seat and leave the four to their own discussion."
        "Join with Haskell":
            $ party01[7] = 1
            "You see Haskell head towards the door. You quickly chase after him."
            show haskell normal with dissolve
            "The sky outside is already dark."
            e "Haskell, are you leaving already?"
            h "I am."
            e "But the party is not over yet."
            h "I'm getting old. I need to head back."
            "You look at the dragon and ask with concern."
            e "Is the party not to your liking? Is that why you're leaving?"
            "Haskell takes his time to answer, making you nervous."
            h "Honestly, I had to think about that. It would have been easier to say yes, but you deserve some honesty, young courier."
            "You notice he has taken more time to think about his words."
            h "I was being frank when I said that I was getting older."
            e "Haskell, you're not that old."
            h "Correct. In dragon years, I'm in my prime. But compared to others, it's hard not to feel ancient."
            e "You feel very young to me."
            "Haskell laughs."
            h "Young courier, you know just what to say to tickle an aged dragon."
            h "Perhaps that's why I've been doing things that I never thought I would."
            e "What do you mean?"
            h "If you must know, I took my first special request for the first time in years."
            h "Granted, it was as troublesome as I thought it would be, but it was quite fulfilling too."
            e "Haskell, you shouldn't have."
            h "You're right. I shouldn't have but I did."
            h "But the overall experience was not bad. It's quite fun helping a young blood establish his new adventure. And this young blood shows a lot of promise too."
            "You blush from the compliment. You feel proud. You know Haskell's compliments are not easy to come by."
            h "I don't mind taking a backseat to an up and coming adventurer."
            h "My adventuring days are behind me but it doesn't mean I can't help another adventurer. So, thanks for showing me that."
            h "You've gotten me more active than ever. Ole will be very appreciative of you. He's always been bugging me to stop being so slovenly."
            e "Haskell, thank you for helping me. Perhaps one day we can go on an adventure together."
            h "Be careful what you wish for young dragon. Once you get this dragon's blood pumping, there's no quenching it."
            "Haskell takes in your whole body. You feel a mixture of anticipation and fear."
            e "Maybe I'm up for the challenge."
            "Haskell raises his brow in surprise and then chuckles with mirth."
            h "Maybe, maybe. Young adventurer, I wonder where your future will take you. In any case, I see great things for you."
            h "But that's for the future. For now, this old dragon has to retire to his hut, for he has an appointment with pots of tea at home."
            "Haskell leaves in the direction of the forest."
    hide haskell
    hide cane
    hide rahim
    hide ole
    hide sebas
    hide amble
    hide jog
    hide lothar
    scene nocturnaltrunk_night
    "Soon, the party is winding down towards its end. Everyone begins dispersing to different corners of the tavern."
    "And Haskell is already gone from the party."
    "You decide to spend one-on-one time with your friends before the day ends."

    "It seems... you have enough time to greet two of your friends."
    call Event_Party01_Loop from _call_Event_Party01_Loop
    hide haskell
    hide cane
    hide rahim
    hide ole
    hide sebas
    hide amble
    hide jog
    hide lothar
    "The party is about to end. You decide to spend the last of it with one of them."
    call Event_Party01_Loop from _call_Event_Party01_Loop_1
    hide haskell
    hide cane
    hide rahim
    hide ole
    hide sebas
    hide amble
    hide jog
    hide lothar
    jump Event_Party01_End
label Event_Party01_Loop:
    scene nocturnaltrunk_night
    menu:
        "Who do you want to check in on?"
        "Cane" if party01[4] == 0:
            $ party01[4] = 1
            call Event_Party01_Cane from _call_Event_Party01_Cane
        "Jog" if party01[6] == 0:
            $ party01[6] = 1
            call Event_Party01_Jog from _call_Event_Party01_Jog
        "Lothar" if party01[2] == 0:
            $ party01[2] = 1
            call Event_Party01_Lothar from _call_Event_Party01_Lothar
        "Sebas" if party01[0] == 0:
            $ party01[0] = 1
            call Event_Party01_Sebas from _call_Event_Party01_Sebas
        "Ole" if party01[1] == 0:
            $ party01[1] = 1
            call Event_Party01_Ole from _call_Event_Party01_Ole
        "Rahim" if party01[3] == 0:
            $ party01[3] = 1
            call Event_Party01_Rahim from _call_Event_Party01_Rahim
        "Amble" if party01[5] == 0:
            $ party01[5] = 1
            call Event_Party01_Amble from _call_Event_Party01_Amble
    return
label Event_Party01_Jog:
    scene nocturnaltrunk_night
    "You wander out the backdoor of the tavern."
    "Jog is sitting on the stoop of the stairs with his back to you."
    show jog normal with dissolve
    "He's juggling a few pebbles with one hand."
    "He looks troubled."
    "Just as you think about turning back, you hear his voice tentatively call out to you."
    j "Since you're already here, why don't you join me and enjoy the night air?"
    "You think about it and slowly ease down to sit beside Jog."
    e "How did you know I was there?"
    "Jog gives you a skeptical look, clearly telling you that you should know why."
    e "Right. Scout."
    j "Not just that. I also know you were listening in on the conversation between Ole and me."
    e "I'm sorry."
    j "Don't need to be. I'm not ashamed of what happened."
    j "I didn't do anything anyway."
    "Jog pauses as if waiting for you to counter him. When you don't, he looks at you with some surprise."
    j "Aren't you going to follow your friends, and condemn me too?"
    e "You know, you're my friend too, Jog."
    e "But no, I'd rather reserve judgement until I hear the full story."
    "Jog chuckles mirthlessly."
    j "A stupid decision, but fine. I'll tell you the story for giving me the benefit of the doubt."
    e "I'm all ears."
    j "Before you moved in, I was actually Seb's roommate."
    j "Shocking, right?"
    j "But I was closer to Ole than Seb. It was Ole who arranged everything. The guy is too kind for his own good, but I was thankful to have a roof over my head."
    e "Then, what happened?"
    j "Jumping straight to the good stuff, are we?"
    j "One day, merchandise in the shop disappeared. Ole and Seb wouldn't steal from themselves so I had to be the culprit."
    e "That's a rather quick conclusion."
    "Jog shrugs."
    j "Eh. My reputation wasn't exactly sparkling clean back then. So, Seb threw me out. Ole did try to help, but he didn't seem that convinced either. I guess I know why now. He doubts me too."
    j "But it worked out for the best."
    e "What do you mean?"
    j "Got rid of those losers and found better company in Boss and Amble."
    j "So things worked out."
    j "Plus, now I have you too. You're much better company than those two."
    "Jog slips his hand up your inner thigh. He uses the back of his hand to nudge your bulge."
    "You shiver. Despite everything, you feel like you understand Jog a bit better now."
    "Could Jog's cheeky persona be his defense mechanism?"
    "You wonder."
    e "I don't know what really happened, but do I trust that you wouldn't maliciously harm your friends. I can see that from how you interact with Lothar and Amble."
    "Jog's wandering hand pauses."
    j "You're a strange guy, but I appreciate it."
    "Jog smacks your inner thigh and stands up."
    j "Anyway, I better go find Amble before the blockhead does anything stupid again."
    return

label Event_Party01_Cane:
    scene nocturnaltrunk_night
    "You find Cane packing stuff in the storeroom."
    "You step into it to join him."
    "Cane turns around to accost you."
    show cane normal with dissolve
    c "I hope ya enjoyed the party, lad, because there's gonna be a lot of cleaning to do tomorrow."
    c "I rather regret lettin' Ole rent this place out for the day."
    c "I mean, who'd a thought a few people'd be messier than a normal day at the tavern?"
    c "Your friends could put right bandits to shame when it comes to partyin'."
    e "'s a sure sign that everyone's havin' themselves good time."
    "Cane looks at you with a raised eyebrow, before promptly smacking you on the ass."
    c "Tryin' ta imitate my accent now lad?"
    c "I appreciate the sentiment, 'specially since it's such a cute lad who's tryin' ta be like this old bat."
    "You hear his accent disappear for a second, like it did with Rahim, as he speaks quietly."
    c "...But you should pick better people to take after."
    "Before you can say anything about what happened, Cane ruffles your head and continues packing up."
    c "Well, I don't exactly see that lot volunteering to help clean up here."
    "Cane lets out a hearty chuckle"
    c "Can't blame 'em, if it weren't my tavern I would a stuck to partying myself!"
    e "I'll be here to help instead."
    c "Good lad. If yer plannin' ta help, lend me a hand with these boxes."
    c "Lothar's gang cleaned me out of most of my liquor stock. I've gotta prepare more for tomorrow."
    "You move to help. As you move the boxes, you continue the conversation."
    e "Rahim is here today. Perhaps you can pay his store a visit in the future."
    "Cane stops moving and narrows his eyes at you."
    c "Whatcha up to?"
    e "Just trying to help the reconciliation."
    c "Don't ya worry yer fuzzy little head about that. I only need ya ta look pretty."
    "Cane continues to move another box."
    c "But thank you."
    "Cane pauses for a long time. Just as he is about to blow you off like usual, he sighs."
    c "It's about that lad we talked about. His name's Topu."
    c "He was one of the most finest lad I've met."
    c "But that brat was a real thrill-seeker. Always taking the most dangerous jobs, making away with m' darn mead."
    "Cane turns to look at you."
    c "Rather like ya. But I'd rather he's out there adventuring like ya do. Instead of doin' whatever it is 'e does."
    c "The brat saw big things for himself. Nothin' wrong with that. But he was always lookin' for shortcuts, y'know?"
    c "Maybe one day, you'll wake up and see yerself as too big for this small little village too."
    e "That won't happen."
    "Cane smiles indulgently at you."
    c "I can bet that yer wrong. Yer meant for greater things. Even this old drunk can see that."
    e "But I don't even know any place beyond the proximity of Lusterfield."
    "Cane looks at you deeply like he can see into your future. Then, he grins."
    c "Kid, just remember that we're not here to bog ya down. When ya get overwhelmed out there, remember that ya have friends at Lusterfield."
    c "Even this old bat is always ready to give ya some physical comfort."
    "Cane's idea of physical comfort is rather unconventional but you appreciate the thought."
    e "Thanks, Cane."
    c "Any day."
    c "Either way, Rahim was there when Topu asked me for money. Saw me reject the brat too."
    c "Guess he must have put 2 and 2 together..."
    e "Oh... But you're not really at fault."
    "Cane shakes his head."
    c "No. I shoulda kept a closer eye on the brat."
    c "Every day I wonder what life'd be like if things could've changed for the better..."
    e "Cane..."
    "Cane exhales as he moves another box."
    c "But that's in the past now."
    c "Now my eye's on ya. I made a promise to rahim... and to myself."
    "You feel quite touched when you felt... touched."
    "Cane's hand runs along your thigh, ruffling your fur as he goes."
    c "After all, it's hard to train another server."
    c "'Specially one who has a nice bod like yours."
    "He says this while pulling your body close to his."
    "You feel the bat's rough fur press against the soft fur of your back, as well as a warm bump pressing greedily against your rump."
    "Just as quickly as it started, the bat ends the embrace, giving your butt a light squeeze and a slap as he pulls away."
    c "Now get back out there and enjoy yerself, lad. Everyone's 'ere to celebrate ya, and ya deserve the break."
    return

label Event_Party01_Lothar:
    scene nocturnaltrunk_night
    "You find Lothar standing outside in the garden."
    "The grass crunches under your feet as you walks towards him."
    show lothar normal with dissolve
    l "Disciple, what you doing out here?"
    e "Lot, are you alright?"
    l "Why wouldn't I be? I'm the Hero of Lusterfield. And call me Lothar."
    e "The confrontation earlier was rather intense. Do you want to talk about it?"
    l "Heroes talk with actions and not words."
    e "Okay. Then, I'll just stand out here and enjoy the night sky with you."
    l "Whatever."
    "You stand there comfortably, feeling the wind on your skin."
    "after a while, Lothar coughs."
    l "Disciple, do you think I'm good company?"
    e "Why would you ask that, Lot?"
    l "You didn't answer the question, Disciple."
    e "Well. I don't mind hanging out with you, Lot."
    "Lothar is quiet for a while."
    l "Of course, you wouldn't, Disciple. I'm the Hero of Lusterfield. It's your honor to spend time with me."
    l "But... Rest of Lusterfield may not feel that way."
    e "What do you mean, Lot?"
    l "I sense little patience in others. And the lion is right about one thing."
    l "I don't get invited to these friendly social events often unless it's from Jog or Amble. But what do they have going on?"
    e "I'm glad you're here at the party."
    l "Of course you are, disciple. Who wouldn't want the Hero at their functions?"
    "Technically, Lothar has already answered that question himself. But you don't say anything lest you hit a sore spot."
    l "Why?"
    "It's a simple word but you understand the meaning behind it."
    e "Perhaps it's because you're the Hero of Lusterfield."
    l "Yes, I am."
    e "But you are more than that Lot."
    "Lothar looks at you with incomprehension."
    e "People might appreciate getting to know Lothar than the Hero of Lusterfield."
    l "But that's who I am."
    e "Lot, you are more than that. I've seen it before."
    if lothar_spar:
        e "Remember when you carried me back after I lost to you?"
        l "You mean when the Hero crushed you and you could barely walk anymore?"

        e "Yes. You carried me back to the shop and cared for me. That shows Lothar's kindness under the name of the Hero."
        l "Yea. Well. A Hero has to take care of everyone here."
    else:
        e "Remember when we had that battle and I bested you?"
        l "You were lucky Disciple. That won't happen again."
        e "Regardless, you chose to honor the terms of our bet."
        if lothar_prize != 2:
            l "That's cause I have faith in the integrity of my Disciple."
            e "Are you sure?"
            l "Of course, you're my Disciple!"
            e "Either way, you're ready to honor the terms and that shows Lothar's humility under the Hero's veneer."
            l "A hero never go back on his words after all."
        else:
            "Lothar's face blushes at the memory."
            l "You won somehow, so a Hero has to honor his words."
            e "That day, I got to see another side of the Hero that not many has seen before."
            l "...Like I said, you squeezed too hard last time."
            l "I'll never promise that again... if we happen to fight."
            e "uhh..."
    e "In conclusion, Lothar, you are more than just the Hero of Lusterfield."
    e "Jog, Amble and I know that."
    e "Maybe you should let others see it too."
    "Lothar is expressionless for a long time. Then, he whips his head from left to right."
    l "Doesn't make sense to me. What can a Disciple teach the Hero of Lusterfield anyway?"
    l "I-... I'm going back in to take advantage of the free drinks before the party's over."
    "Lothar saunters away. You notice the usual spring is back in the Hero's steps."
    return
label Event_Party01_Sebas:
    scene nocturnaltrunk_night
    "You see Seb pacing around the tavern corridor."
    "When he sees you, he doesn't greet you as enthusiastically as he normally would."
    show sebas normal with dissolve
    e "Seb, what's wrong?"
    s "Roomie, I'm sorry."
    e "What for?"
    s "For ruining your party. This is supposed to be fun but I had to get into an argument with that stupid wolf."
    s "I've calmed down after talking to Ole and realized how it must have affected your party. So I'm sorry."
    e "Seb, I don't mind."
    "Sebas cracks a small smile."
    s "Roomy, you don't know how happy I am to hear that, but I'm still sorry."
    e "Stop apologizing. By the way, why did you get into the argument with Lothar?"
    "Sebas groans with annoyance."
    s "I didn't even wanted to invite the stupid wolf, but Ole said that the wolf has been featured in your life at Lusterfield too."
    s "You know how insistent Ole can be on pleasing everyone."
    e "I do know that."
    s "And... you saw what happened."
    "Sebas pouts."
    e "Seb, why didn't you want Lothar to come anyway?"
    s "It's you, Roomy."
    e "Me?"
    s "Yea. You've been spending too much time with the wolf."
    "You raise your brows."
    e "Are you jealous, Seb?"
    "Seb smacks you jokingly."
    s "Roomie, what if I say that I am?"
    s "But that's not the real reason."
    e "Aw, I was hoping that was the real reason. But what is it?"
    s "The wolf mixes with the wrong kind of crowd."
    s "Amble is better, but the other..."
    s "His team is nothing more than a ragtag group of gangsters."
    e "Perhaps after you know them..."
    s "I know them well enough."
    s "I just don't want them to have a bad influence on you."
    s "You're supposed to be my good Roomy, not off forming gangs with the stupid wolf."
    if not sebas_kick:
        e "You worry too much, Seb. Nothing like that is happening."
        s "Am I? You didn't even side with me when I could have gotten my revenge on the wolf with a kick back to his nuts."
        e "How is that the same thing? I just don't want to see any other nuts casualty."
        s "But what about my nuts?"
        e "What about them?"
        "You smirk."
        s "Very slick, buddy."
    else:
        e "Clearly, that's not happening. Haven't I helped you take revenge by allowing you to kick Lothar's back?"
        e "Would I do that if I'm in some sort of gang with them?"
        "Sebas taps his chin."
        s "Guess you're right..."
    s "But still, I can't help but worry. I've seen the same thing happen with Ole."

    s "I'm not going to watch my Roomy fall into the clutches of the stupid Wolf."
    e "Seb, I appreciate the concern. But by your same logic, if they can influence me, I'd be influenced by you and Ole too."
    e "Knowing that I have your care will make sure that I'll not stray from the right path."
    s "ROOMY, you're right! That's a great idea!"
    "Sebas runs into you and pulls you into a tight embrace."
    s "I'm going to infuse my influence into you so that you'd never be led astray by the stupid wolf."
    "Seb rubs his fur against yours. It's very ticklish."
    if sebas_suck:
        "Suddenly, you feel a firm grab on your ass."
        s "I might have other ways that I can lay influence into my fluffy roomie."
        e "Seb, stop joking. We're in public."
        s "Fine, fine. But we do need to find a more discreet place to resume what you started."
        s "Last time I almost got caught by a customer because of it."
        "You scratch behind your ears shyly."
        e "Sorry."
        s "Well, it was fun, isn't that what it's all about."
    e "You're being silly, Seb."
    "Seb continues to hug you tight until Seb feels it is enough to fend out the wolf's influence."
    return
label Event_Party01_Ole:
    scene nocturnaltrunk_night
    "You spot Ole cleaning up after the others."
    "You shake your head helplessly as you walk over to help."
    show ole normal with dissolve
    o "[e], you don't need to do this. It's your party."
    e "Ole, it's not like you need to do this either. We're not back at the shop."
    "Ole flushes from embarrassment."
    o "It's fine. I like helping out. Plus, we've made a mess. We better clean up before Cane gets mad."
    e "Then, let me help you. At least I work here part time. I have more of a reason to help out than you do."
    "As you move to clean up the empty mugs and plates, Ole sighs and obliges."
    "After you two clean up a table, you grab Ole and stop him."
    e "Ole, I think you deserve a rest."
    o "I'm fine..."
    "You interrupt him."
    e "This is my party. At least, have fun."
    "You smile at him."
    e "If you really need to find something to do, talk with me."
    "Ole acquiesces."
    o "Alright. What is it that you want to talk about?"
    e "Thank you."
    o "What for?"
    e "For this."
    "You gesture at the party around you."
    o "I didn't do anything. This is Seb's idea. You should thank him."
    e "Don't undersell yourself. Like you said, Seb can't just come up with all the planning on his own. You've done a lot and I want to thank you for it."
    o "It's no problem. I like to help."
    "You nudge him."
    e "Yes, but you have to take a breather too."
    o "What do you mean?"
    e "We don't want the incident from last time to happen again, do we?"
    "Ole lowers his head."
    o "..."
    e "Brighten up, Ole. I don't mean to bring the mood down. I'm just saying that we need to help ourselves before we can help others."
    o "It's not that. I really appreciate the concern, but you're wrong."
    e "Oh?"
    o "I mean I don't mind that incident happening again... especially the last part with you and me..."
    "You swear Ole is about to burn from the embarrassment."
    "You grin."
    e "Ole, I have no idea you're so naughty."
    o "N-no. It's not that. It's just I've been thinking about it since that day."
    e "Honestly? Me too."
    e "I wouldn't mind doing more with you."
    "Ole blushes violently."
    o "But I have no experience at all with these things..."
    if sebas_suck:
        "Then something comes to your mind and it's your turn to be embarrassed."
        e "Ole... What about... you know... the thing you saw... with Seb and me... under the table."
        o "T-that's fine... I don't mind if you don't mind."
        "You believe that's the limit with Ole because Ole stops talking and starts to furiously clean a spot on the table."
    e "Then, this the perfect chance for us to help each other. We'll explore and help each other!"
    o "Hmm..."
    o "Now I think, we shouldn't do this too often."
    o "I don't want folks to see how... not me. I was."
    e "You do not enjoy it?"
    o "I do."
    o "But, that wasn't who I am."
    e "...Ole?"
    o "Sorry, I'm not used to talk about myself this much."
    "The lizard ponders for a moment."
    "Ole grabs your hand, he is holding it tight. His nails dig deep into your palm."
    o "Let's say. we can spend more time on doing other stuff together."
    "You can feel his warmth soon spread across your body. You are stunned for a second."
    e "W-what do you mean."
    "His thumb sweeps your palm lightly, before letting you go."
    "You feel Ole presses against your snout."
    o "I feel like you are getting excited for the wrong reason."
    o "But... I'll sleep on it."
    return
label Event_Party01_Rahim:
    scene nocturnaltrunk_night
    "You squeeze into the seat across from Rahim."
    "You notice that Rahim is a lot more relaxed than when you talked to him earlier."
    "Perhaps his talk with Cane has loosened many things within him... or perhaps it's the alcohol."
    show rahim normal with dissolve
    e "Rahim, are you alright?"
    r "Why wouldn't I be?"
    e "Well... I kinda overheard your conversation with Cane earlier."
    "Rahim becomes silent. You fear that he might be angry for the eavesdropping."
    "After a while, Rahim heaves a large sigh and his body droops."
    r "I guess we weren't trying to hide it. And this is a public place..."
    "Rahim looks around as if seeing things there that you can't."
    r "But you're right. Being here is rather strange. It's hard not to see the traces of Topu everywhere."
    e "Rahim, if you don't want to talk about this, I can..."
    "Rahim waves his hands."
    r "I owe you this much."
    r "Cane and I have been talking you around this person that you've not even met. That's unfair to you."
    e "It's fine. I understand."
    r "... That's why you are so similar and yet so different from Topu."
    e "What do you mean?"
    r "He would have stayed to listen too, but I'm not sure if he would have understood."
    r "The kid has never been much of a listener."
    e "He must be special to have you and Cane cherish him that much."
    "Rahim takes another sip of the beer and a frown appears between his brows."
    r "... He's not perfect."
    e "What do you mean?"
    r "If I have handed him the same quest to gather the feedback on the clothes, he would have figured out a way to get all three sets from me. And I would have let him."
    r "He just has this charm about him."
    r "But you've never considered doing that."
    e "Thanks?"
    r "Sadly, he has followed the wrong mentor."
    "Rahim glances up at the counter where Rahim is."
    "Instead of anger, there is an underlying layer of regret in Rahim's eyes."
    "Then, Rahim trains his eyes on you."
    r "Kid, if there's anything to learn here, it's that you have a wide support system."
    r "If you ever run into any trouble, come to me..."
    "You are touched by Rahim's sincerity."
    e "Rahim, thank you."
    "Rahim grunts and he reverts to his usual bullish self."
    return
label Event_Party01_Amble:
    scene nocturnaltrunk_night

    "At the party, Amble immediately draws your attention."
    "He appears to be juggling a handful of jugs with his massive arms."
    "You walk over and offer to help."
    show amble normal with dissolve
    e "Amble, what are you doing? And is there anything I can do to help? You look like you have your hands full."
    "Amble peeks over the jugs of beer and breaks into a smile when he sees you."
    a "Puny friend, it's you!"
    e "So, what are you doing?"
    a "I'm trying to juggle as many beer jugs as I can."
    "Amble shifts his weight as one of the jugs teeters dangerously."
    a "Phew, that was close."
    e "Erm... Amble... Why are you doing this?"
    a "Cause I am in on a bet!"
    e "What bet?"
    a "A bet with cane! He bets that I can't juggle more than five jugs at the same time."
    a "I am always ready to prove him wrong!"
    "Plus, if I can hold them for more than 10 minutes, I get to drink them all!"
    "If you had to take a guess, Cane is setting up a bet based on whether Amble can accomplish this feat or not."
    "From the looks of it, most are betting against Amble."
    e "No. I mean Cane is using you to start a bet of his own."
    a "Oh. I know about that. I'm betting that I'd win too."
    e "And Cane allowed that?"
    a "Why wouldn't he? Everything deserves a fair chance, right?"
    "Technically, that is not right."
    "Cane knows that Amble has a stake in winning the bet for both the money and the drinks."
    "So he must have persuaded the others to bet against Amble winning."
    "However, since everyone is willing to play along, you decide you would too."
    e "Yea, you're right. I'll be supporting you then."
    a "Thanks, puny friend!"
    a "Glad to know you're on my side!"
    scene black with dissolve
    scene nocturnaltrunk_night with dissolve
    "Minutes later, Amble waves you over."
    a "Hey, puny friend. Come join me!"
    "The jugs of beer are spread on the table."
    e "Looks like you've won."
    a "Sure did!"
    "Amble pushes a jug of frothy beer to you."
    a "And this is for you!"
    e "Me? Thanks. But why?"
    a "You were on my side and gave me support. This is the least I can offer you back!"
    e "Thanks, Amble!"
    a "Welcome, puny friend!"
    "Amble bumps his beer against yours."
    return
label Event_Party01_End:
    hide sebas
    hide lothar
    hide amble
    hide jog
    hide ole
    hide rahim
    hide cane
    "The party eventually reaches its end."
    "Your friends leaves the tavern one by one."
    "You bid farewell to them at the door."
    "Cane closes the door behind you."
    "You walks on home with Seb and Ole."
    "You take in the surroundings of Lusterfield."
    "It is not Puro. And your clanspeople are not here."
    "What happened to Chime remains unanswered."
    "But at least... Lusterfield is starting to feel a bit more like home."
    $ timenow.hour = 22
    $ QuestFinish(quest16)
    jump main_lusterfield02
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
