translate schinese_rewrite strings:

    old "Date: 15th of Frostfall\n\nEntries:\n1. {b}10 pieces of Rahim's Small Cloth{/b}\nNotes: Excellent condition, it's Rahim so it must be good.\nPurchase Price: 1 Gold\n\n2. {b}Wide-brimmed Hat of Sorcery{/b}\nCondition: Excellent, albeit some burn and wear on the brim\nNote: Recovered from the wild ruins near the dark forest\nPawned by: Ferrit the sorcerer, with a purple staff, he looks like a lion but his mane's not as majestic as mine.\nLoan Amount: 450 Gold\nRedemption Due Date: 15th of Sproutsong"
    new "日期：霜落月15日\n\n条目：\n1. {b}雷希姆的小布料×10{/b}\n备注：状况极佳，毕竟是雷希姆的东西，肯定不会差。\n收购价：1枚金币\n\n2. {b}巫术阔檐帽{/b}\n状况：极佳，不过帽檐有些烧痕和磨损\n备注：从黑暗森林附近的荒野遗迹中找到\n典当人：巫师费里特，他拿着一根紫色法杖，看起来像头狮子，不过他的鬃毛可没我的威风。\n借款金额：450枚金币\n赎回期限：萌芽歌月15日"

    old "3. {b}3 bottles of Small Health Potions{/b}\nNotes: Excellent condition, gotta start pressing Haskie to make more of them potions, Ole, is it that hard to juice up some red berries???\nPurchase Price: my soul for walking a whole hour for 3 potions\n\n4. {b}Likkathian Iron Helmet{/b}\nCondition: Excellent, except the left side is completely destroyed by fire magic, most of the right side is burned to a crisp.\nNote: Recovered from a retired soldier in Likkathia\nSell by: duh\nPurchase Price: 10 gold"
    new "3. {b}小型治疗药水×3瓶{/b}\n备注：状况极佳，得开始催哈斯基多做些这种药水了。奥利，榨几颗红浆果有那么难吗？？？\n收购价：为了走整整一小时换来3瓶药水，我连灵魂都赔上了\n\n4. {b}利卡希亚铁盔{/b}\n状况：极佳，不过左侧被火焰魔法彻底毁掉了，右侧大半也被烧得焦黑。\n备注：从利卡希亚的一名退役士兵那里找到\n售出人：废话\n收购价：10枚金币"

    old "5. {b}Book of Fiery Charge{/b}\nCondition: Excellent, some wear on the bottom corner in the back\nNote: Recovered from Ole's {i}friends{/i}, been in his collections for a long time\nSold by: Ole, it's fucking Ole\nPurchase Price: 0 gold\n\n6. {b}Crystal Orb of Mending{/b}\nCondition: Excellent, but it's a bit used\nNote: Seems to be popular among the healers, he gotta get it back quick or we'll sell it to someone else\nPawned by: Baird the scavenger, the frog dude living next to Rahim.\nLoan Amount: 300 Gold\nRedemption Due Date: 24th of Frostfall"
    new "5. {b}烈焰冲锋之书{/b}\n状况：极佳，背面底角有些磨损\n备注：从奥利的{i}朋友们{/i}那里找到，已经在他的收藏里放了很久\n售出人：奥利，妈的就是奥利\n收购价：0枚金币\n\n6. {b}修复水晶球{/b}\n状况：极佳，不过有点用旧了\n备注：似乎很受治疗师们欢迎。他得赶紧把它赎回去，不然我们就卖给别人了\n典当人：拾荒者拜尔德，就是住在雷希姆旁边的那个青蛙人。\n借款金额：300枚金币\n赎回期限：霜落月24日"

    old "7. {b}Steel Dagger{/b}\nCondition: Excellent, pristine even.\nNote: Straight out of the anvil, looks good.\nPawned by: Pickard the blacksmith, he never redeems his weapon, should've just sold them\nLoan Amount: 55 Gold\nRedemption Due Date: 12th of Suncrest\n\n8. {b}Sapphire Necklace of Vitality{/b}\nCondition: Excellent\nNote: says it's gilded with pure gold, but it's not reflective enough, not sure if it's real, gotta need an appraiser like Gwyd\nPawned by: Hooded guy, can't hear half of what he says\nLoan Amount: 120 Gold\nRedemption Due Date: 30th of Frostfall"
    new "7. {b}钢匕首{/b}\n状况：极佳，甚至崭新如初。\n备注：刚出铁砧，看起来不错。\n典当人：铁匠皮卡德，他从来不赎回自己的武器，早该直接卖掉了\n借款金额：55枚金币\n赎回期限：日冠月12日\n\n8. {b}活力蓝宝石项链{/b}\n状况：极佳\n备注：他说这条项链镀的是纯金，但它的反光不够强，我不确定是不是真的。看来得找格威德那样的鉴定师才行\n典当人：戴兜帽的家伙，他说的话我有一半都听不清\n借款金额：120枚金币\n赎回期限：霜落月30日"

    old "9. {b}Likkathian Iron Helmet{/b}\nCondition: Excellent, the seller should put it on himself\nNote: Nah\nPurchased by: duh\nSale Price: 3000 gold\n\n10. {b}Ring of Eldest{/b}\nCondition: Excellent, it sounds just as cheesy as it should\nNote: Not to be confused with another ring, this one is cosmetic only, referenced by the northern supplier\nTraded for: Crystal Orb of Mending, gotta say sorry to Baird."
    new "9. {b}利卡西亚铁盔{/b}\n状况：极佳，卖家自己就该把它戴上\n备注：没什么\n购买者：废话\n售价：3000金币\n\n10. {b}长老之戒{/b}\n状况：极佳，听起来就该这么俗气\n备注：别和另一枚戒指搞混了，这枚仅用于装饰，是北方供应商提到的那枚\n交换所得：修复水晶球，得跟拜尔德说声抱歉。"

    old "11. {b}Elixir of Fleeting Agility{/b}\nCondition: Excellent, never opened before.\nNote: Seems to be a rip-off of Haskie's old recipe, looks good though.\nSold by: Andri the travelling merchant\nPurchase Price: 60 Gold\n\n12. {b}Rock Sculpture of Tapjoo{/b}\nCondition: Excellent, small crack in the bottom\nNote: Seller refused to elaborate on the origin but this is real old, matches Tapjoo's mask in other goat painting so it's legit\nSold by: Another Hooded guy, with horn this time.\nPurchase Amount: 2150 Gold"
    new "11. {b}短暂敏捷药剂{/b}\n状况：极佳，此前从未开封。\n备注：似乎是仿制哈斯基的老配方，不过看起来还不错。\n出售者：旅行商人安德里\n购入价：60金币\n\n12. {b}塔普乔的岩石雕像{/b}\n状况：极佳，底部有一道小裂缝\n备注：卖家拒绝详述它的来历，但这东西确实非常古老，和另一幅山羊画中的塔普乔面具相符，所以货真价实\n出售者：另一个戴兜帽的家伙，这次还长着角。\n购入金额：2150金币"

    old "13. {b}Old Bronze-plated Armor{/b}\nCondition: Excellent\nNote: it was pretty lame, get it Ole? Lame? \nPawned by: Ludvar the wolf, he keeps bugging me about the price\nLoan Amount: 301 gold\nRedemption Due Date: Negotiable\n\n14. {b}Copy of the History of Otsovaara{/b}\nCondition: Excellent?\nNote: Sturdy paper, clean handwriting but too modern for any scholar with self-respect. \nSale Price: 40 Gold"
    new "13. {b}旧青铜甲{/b}\n状况：极佳\n备注：确实挺差劲的，明白吗，奥利？差劲？\n典当者：狼族路德瓦尔，他一直纠缠着问我价格\n贷款金额：301金币\n赎回期限：可协商\n\n14. {b}《奥茨瓦拉史》副本{/b}\n状况：极佳？\n备注：纸张结实，字迹工整，但对任何一个有自尊的学者来说都太现代了。\n售价：40金币"

    old "15. {b}12 pieces of Werewolf Pelts{/b}\nCondition: Excellent, freshly harvested.\nNote: The hunters are on their hunt again, will pass this to Rahim later, {i}no werewolves involved are hurt during this process, I think.{/i}\nSold by: Est the leader\nPurchase Price: 240 Gold\n\n"
    new "15. {b}12张狼人皮{/b}\n状况：极佳，刚刚剥下。\n备注：猎人们又出去打猎了，之后会把这些交给雷希姆，{i}我想，整个过程中应该没有狼人受伤。{/i}\n出售者：首领埃斯特\n购入价：240金币\n\n"

    old "Moss\nAn unusual occurrence today has piqued my curiosity. While overseeing routine maintenance in the longhouse, I noticed a faint draft emanating from behind the old tapestry of the harvest. It's strange, considering that wall has no doors or windows. On closer inspection, I found a hidden seam in the wooden paneling. Armed with a lantern and a sense of intrigue, I ventured down the steps. The air grew cooler, carrying the scent of damp earth and aged stone. At the bottom, I discovered a small chamber with walls adorned in faded symbols and carvings — figures cloaked and hooded, holding staffs, and intricate patterns resembling flowing water or the river itself."
    new "苔藓\n今天发生了一件不同寻常的事，勾起了我的好奇心。我在长屋监督日常维护时，注意到一股微弱的气流从丰收旧挂毯后方吹来。考虑到那面墙没有门窗，这实在奇怪。仔细查看后，我在木板之间发现了一道隐藏的接缝。我带上提灯，怀着探究的兴致走下台阶。空气越来越冷，带着潮湿泥土与古老石头的气味。到底部后，我发现了一间小小的密室，墙上布满褪色的符号与雕刻——有些身披长袍、戴着兜帽、手持法杖的人形，还有些精细的图案，像是流动的水，或是河流本身。"

    old "In the center stood a simple stone mural, unadorned yet commanding. The atmosphere was thick with an indefinable weight, as if the room itself was holding its breath. I felt an inexplicable pull, a whisper at the edge of consciousness urging me to delve deeper. I attempted to discuss with Irm, the steward, hoping he might shed some light on its origin. He seemed genuinely puzzled, assuring me that no records mention any subterranean structures beneath the longhouse. Sleep did not come easily tonight. My dreams were vivid — a dense forest bathed in silver moonlight, shadows stretching and twisting among the trees. Amidst the darkness, a pair of orange, luminous eyes watched me intently. I awoke unsettled but oddly compelled to return to the hidden chamber."
    new "中央立着一幅简朴的石雕壁画，毫无装饰，却自有一股威严。空气中弥漫着一种无法名状的沉重感，仿佛连房间本身都屏住了呼吸。我感到一股莫名的牵引，意识边缘传来低语，催促我继续深入。我试着和管事伊尔姆谈起此事，希望他能解释它的来历。他似乎确实感到困惑，向我保证说，没有任何记录提到长屋下方存在地下建筑。今晚我久久无法入睡。梦境异常清晰——一片浓密的森林沐浴在银色月光下，阴影在树木间不断延伸、扭曲。黑暗中，一双橙色的发光眼睛正专注地注视着我。我醒来时心神不宁，却又莫名想要回到那间密室。"

    old "Shepherd\nSeveral days have passed since my initial descent, and the hidden depths beneath the longhouse occupy my every thought. Each evening, under the guise of extended duties, I return to explore further. The chamber I first discovered is but an antechamber to a more extensive network of rooms and passageways. As I navigate this labyrinth, I find that the walls themselves seem alive with meaning. The symbols and carvings, once obscure, begin to form patterns—repeating motifs of Tapjoo's staff. There are depictions of figures following the old god, their faces indistinct but their postures reverent. The puzzles I encounter are intricate yet intuitive, as if designed to be solved by a specific person or type of person."
    new "牧羊人\n自我第一次下到那里以来，已经过去好几天了，长屋下方的隐秘深处占据了我的全部思绪。每天傍晚，我都借口要延长工作时间，回去继续探索。我最初发现的那间密室，不过是通往更庞大房间与通道网络的前厅。当我在这座迷宫中穿行时，发现墙壁本身仿佛蕴含着鲜活的意义。那些曾经晦涩难明的符号与雕刻，开始组成某种图案——反复出现的塔普乔法杖纹样。墙上还描绘着追随那位古神的人形，他们的面孔模糊不清，姿态却充满敬意。我遇到的谜题精巧而又直观，仿佛是专门为某个特定的人，或某类人设计的。"

    old "Stone doors yield to pressure applied in certain sequences, and pathways open when patterns are traced upon the walls. My conversations with the steward grow strained. He remarks on my frequent absences from communal gatherings. I offer vague explanations about clerical duties and village records, but I sense his growing concern. The eyes in the forest have become a recurring presence, watching me with what feels like expectation. Last night, the dream changed. The eyes drew closer, and I could make out a figure — a shepherd cloaked in shadows, holding a staff that glinted in the moonlight. He extended his hand as if inviting me to follow. I awoke with a start, the image seared into my mind, and my horns ached greatly."
    new "石门会在按照特定顺序施加压力后开启，墙上描出图案时，也会有道路显现。随着我和管事的交谈增多，气氛变得越来越紧张。他提到我经常缺席集会。我含糊地解释说是在处理文书事务和村庄记录，但我能感觉到他的担忧正在加深。森林中的那双眼睛已成了反复出现的存在，以一种仿佛在期待什么的目光注视着我。昨晚，梦境变了。那双眼睛靠得更近了，我看清了一个身影——一个披着阴影、手持法杖的牧羊人，法杖在月光下闪闪发亮。他伸出手，仿佛在邀请我跟随。我猛然惊醒，那幅画面深深烙在脑海中，双角也疼得厉害。"

    old "Horns\nTime has become fluid. Days blend into nights without distinction. I find myself losing hours, emerging from the depths to find the sun setting when I thought it had just risen. The temple—there is no other word for it—has a hold on me that I cannot break, nor am I certain I want to. I've begun to piece together more of the inscriptions - {i}Only those who bear the sacred crowns of nature shall hear Tapjoo's whispers. Through the horns that touch the sky, his wisdom flow like rivers unseen.{/i} Almost immediately I touched my horns, it feels warmer than any other part of my body. I can't help but feel that I am retracing their steps."
    new "角\n时间变得流动不定，白昼与黑夜混在一起，再无分别。我发现自己会无故失去数小时，从深处出来时，明明以为太阳才刚升起，却发现它已经西沉。这座神殿——除此之外，我想不出别的称呼——牢牢攫住了我，我无法挣脱，也不确定自己是否想要挣脱。我开始拼凑出更多铭文的含义——{i}只有拥有自然神圣冠冕之人，才能听见塔普乔的低语。通过触及天穹的双角，他的智慧如无形之河般流淌。{/i}我几乎立刻摸了摸自己的双角，感觉它们比身体其他部位都温暖。我不禁觉得，自己正在重走他们走过的路。"

    old "The challenges, the symbols, the pervasive presence of the old god — all seem tailored to lead me toward some revelation. Yet, doubt gnaws at me. Is this a path to wisdom, or am I being led astray by forces I do not understand? The steward's concern has turned to suspicion. He mentioned rumors circulating among the villagers — whispers of strange lights seen in the longhouse at odd hours, of the mayor neglecting his duties. I attempted to allay his fears, but I sense a growing rift. The eyes haunt me still, no longer confined to dreams. In the forest beyond the village, I feel their gaze upon me. During council meetings, I catch reflections in the window that do not match the room. The line between reality and illusion is blurring."
    new "这些考验、符号，以及那位古神无处不在的气息——似乎全都被精心安排，引领我走向某个启示。然而，怀疑啃噬着我。这是一条通往智慧的道路，还是我正被某种无法理解的力量引入歧途？管事的担忧已变成了怀疑。他提到村民间流传的传闻——有人低声议论，说在不寻常的时辰曾看到长屋里亮起奇异的光，还说镇长疏于履行职责。我试图消除他的疑虑，但能感觉到裂痕正在扩大。那双眼睛仍然萦绕不去，不再只存在于梦中。在村外的森林里，我能感受到它们的注视。参加议事会时，我会在窗户中瞥见与房间不相符的倒影。现实与幻觉之间的界线正在变得模糊。"

    old "Altar\nThis may be my final entry. I stand at a precipice. The temple's final chamber lies before me, its entrance sealed by a complex mechanism that requires not just physical keys but an alignment of symbols and, I suspect, intent. I've gathered the artifacts found throughout the temple—a set of engraved stones, each bearing a unique symbol. Arranging them in what I believe to be the correct configuration, the door began to open, but stopped short. It seems there's one piece missing, or perhaps a final act required of me that I have yet to discern. The steward confronted me today with an ultimatum. He demands that I refocus on my responsibilities or consider stepping down."
    new "祭坛\n这或许是我最后一篇记录。我站在悬崖边。神殿的最终房间就在眼前，入口被一道复杂的机关封锁着；开启它不仅需要实体钥匙，还需要将符号排列对应，而我怀疑，还需要某种意图。我收集了神殿各处找到的遗物——一组刻有图案的石头，每块石头都带有独特的符号。我按照自己认为正确的配置将它们排列起来，门开始开启，却在即将打开时停住了。似乎还缺少一件东西，或者还需要我完成某个最后的举动，只是我尚未弄清那是什么。今天，管事来找我摊牌。他要求我重新专注于自己的职责，否则就考虑辞职。"

    old "He speaks of the welfare of the village, the trust placed in me. His words are reasonable, but they feel distant, as if coming from another world. That night, the dreams returned with a vengeance. The eyes were closer than ever, the shepherd's figure looming. This time, he spoke — a single phrase that echoed in my mind even after waking: 'The shepherd comes for us all.' I don't know what it means, but it fills me with equal parts dread and anticipation. I leave this journal behind for whoever may find it. Perhaps the steward, perhaps another drawn by the temple's allure. My path leads elsewhere now. I will enter the final chamber tomorrow, with or without the missing piece."
    new "他谈论着村子的福祉，以及人们对我的信任。他的话合情合理，却让我觉得无比遥远，仿佛来自另一个世界。那天夜里，梦境卷土重来，而且来势更加凶猛。那双眼睛离得前所未有地近，牧羊人的身影高高压迫而来。这一次，他开口了——只有一句话，却在我醒来后依然回荡在脑海中：“牧羊人会找上我们所有人。”我不知道这意味着什么，但它让我既感到恐惧，又隐隐期待。我把这本日记留在这里，给任何找到它的人。也许是管事者，也许是另一个被神庙魅力吸引而来的人。如今，我的道路通向别处。无论缺失的那一块是否找到，我明天都将进入最终的房间。"

    old "Dragon\nToday, before my search for answers, I stumbled upon an ancient parchment hidden within a concealed compartment in one of the temple's outer chambers. The parchment is fragile, its edges crumbling at the touch, but the ink remains legible. It appears to be a prophecy or perhaps a warning. It speaks of a horned dragon that slumbers beneath the earth, bound by chains forged of forgotten oaths. The dragon is said to awaken when the shepherd's call reaches the depths, heralding a time of upheaval and transformation. I can't help but wonder if this prophecy is connected to the chamber I cannot yet access. Is the horned dragon a metaphor, or does something more literal lie beneath the temple? The idea both fascinates and unsettles me."
    new "龙\n今天，在寻找答案之前，我偶然在神庙外侧某个房间的暗格里发现了一张古老的羊皮纸。羊皮纸十分脆弱，边缘一碰就会碎裂，但上面的墨迹仍然清晰可辨。那似乎是一则预言，又或许是一种警告。上面说，有一条长着角的龙沉睡在大地之下，被遗忘的誓言铸成的锁链束缚着。据说，当牧羊人的呼唤传至深渊时，巨龙便会苏醒，宣告一场动荡与蜕变的时代到来。我不禁怀疑，这则预言是否与那间我尚无法进入的房间有关。那条角龙只是个隐喻，还是说，神庙之下真的潜藏着更为具体的存在？这个想法既令我着迷，也让我隐隐不安。"

    old "The search has drained my entire body unto exhaustion, my will dwindles but my determination unchanged. I had decided to rest before my final search commences at night. I only dread meeting the shepherd again, his words did not stop resonating in my mind. May the old gods watch over me."
    new "这场搜寻耗尽了我的体力，我的意志日渐衰退，但决心依然未变。我决定先休息，等夜里再开始最后的搜寻。我唯一害怕的，就是再次遇见牧羊人；他的话始终在我脑海中回响不止。愿古老的诸神庇佑我。"

    old "Day 1214\nAin't we just the luckiest sons of benches? We've been robbin' folks left and right, and our coffers are brimming with shiny bits and bobs. Here's what we've got to show for it:\n\n10 flowin' robes of silk. We'll probably sell these to some rich fool in the city who's willing to pay through the nose for some fancy cloth.\nA roll of paper, Looka told us it's an old poem about some hero and monster, forgot what he said. We took it from that bard who's been making noise outside, should fetch a good price with it.\nThink we've got like, whole lotta gold tradin some goods, Buck's gonna get us some good wine today."
    new "第1214天\n我们难道不是世上最走运的板凳之子吗？我们到处抢劫，把人们搜刮得干干净净，钱箱里都塞满了闪闪发亮的零碎玩意儿。看看，这就是我们这趟的收获：\n\n10件飘逸的丝绸长袍。我们大概能把它们卖给城里某个有钱的蠢货，那家伙肯为几块花哨布料付出天价。\n一卷纸。卢卡告诉我们，那是一首关于某个英雄和怪物的古老诗歌，我忘了他说的具体内容。我们从那个一直在外面吵闹的吟游诗人那里抢来的，应该能卖个好价钱。\n我寻思着，我们拿一些货物换来了老大一笔金子，巴克今天会给我们弄些好酒来。"

    old "Day 1215\nWe had ourselves a real good time the other night. We got drunk on wine and told stories of our exploits. \nSpeaking of selling things, we managed to offload that piece of paper from the bard to a fence we know in the village. Got a good price for it too. 3000 gold right in our pocket.\n\nWe took some other stuff also:\n25 pieces of iron ore, think some werewolves came out of nowhere and delivered them right at our doorstep.\n1 magical wand, swiped from a traveling wizard. We're not sure what to do with this yet, so we'll hold on to it for a bit."
    new "第1215天\n前几天晚上我们玩得可真痛快。我们喝酒喝到醉，还讲起了自己的战绩。\n说到卖东西，我们已经把从吟游诗人那里拿来的那张纸卖给了村里一个熟悉的销赃人。价格也相当不错，整整3000枚金币已经进了我们的口袋。\n\n我们还弄到了些别的东西：\n25块铁矿石，我猜是些狼人突然冒出来，把它们直接送到了我们家门口。\n1根魔杖，从一个云游巫师那里顺手拿来的。我们还没想好该拿它怎么办，所以暂时先留着。"
