translate schinese_rewrite strings:

    old "Date: 15th of Frostfall\n\nEntries:\n1. {b}10 pieces of Rahim's Small Cloth{/b}\nNotes: Excellent condition, it's Rahim so it must be good.\nPurchase Price: 1 Gold\n\n2. {b}Wide-brimmed Hat of Sorcery{/b}\nCondition: Excellent, albeit some burn and wear on the brim\nNote: Recovered from the wild ruins near the dark forest\nPawned by: Ferrit the sorcerer, with a purple staff, he looks like a lion but his mane's not as majestic as mine.\nLoan Amount: 450 Gold\nRedemption Due Date: 15th of Sproutsong"
    new "霜落月15日\n\n条目：\n1. {b}拉希姆的10件小布料{/b}\n备注：品相极佳，毕竟是拉希姆的货。\n购入价：1金币\n\n2. {b}宽檐巫术帽{/b}\n品相：极佳，不过帽檐有些烧痕和磨损\n备注：从黑暗森林附近的荒废遗迹中回收\n典当人：巫师费里特，拿着紫色法杖。他看起来像头狮子，但鬃毛可没我的威风。\n借款：450金币\n赎回期限：芽生月15日"

    old "3. {b}3 bottles of Small Health Potions{/b}\nNotes: Excellent condition, gotta start pressing Haskie to make more of them potions, Ole, is it that hard to juice up some red berries???\nPurchase Price: my soul for walking a whole hour for 3 potions\n\n4. {b}Likkathian Iron Helmet{/b}\nCondition: Excellent, except the left side is completely destroyed by fire magic, most of the right side is burned to a crisp.\nNote: Recovered from a retired soldier in Likkathia\nSell by: duh\nPurchase Price: 10 gold"
    new "3. {b}3瓶小型生命药水{/b}\n备注：品相极佳。哈斯基，你该多做些这种药水了；欧勒，把红莓榨成汁有那么难吗？？？\n购入价：为了走一小时去买3瓶药水，代价是我的灵魂\n\n4. {b}利卡希亚铁盔{/b}\n品相：极佳，不过左侧被火系魔法彻底毁掉，右侧大半也烧得焦黑。\n备注：从利卡希亚的一名退役士兵手中回收\n售价：呃，随便吧\n购入价：10金币"

    old "5. {b}Book of Fiery Charge{/b}\nCondition: Excellent, some wear on the bottom corner in the back\nNote: Recovered from Ole's {i}friends{/i}, been in his collections for a long time\nSold by: Ole, it's fucking Ole\nPurchase Price: 0 gold\n\n6. {b}Crystal Orb of Mending{/b}\nCondition: Excellent, but it's a bit used\nNote: Seems to be popular among the healers, he gotta get it back quick or we'll sell it to someone else\nPawned by: Baird the scavenger, the frog dude living next to Rahim.\nLoan Amount: 300 Gold\nRedemption Due Date: 24th of Frostfall"
    new "5. {b}烈焰冲锋之书{/b}\n品相：极佳，背面底角有些磨损\n备注：从欧勒的{i}朋友们{/i}那里回收，已经在他的收藏里很久了\n卖家：欧勒，妈的就是欧勒\n购入价：0金币\n\n6. {b}修复水晶球{/b}\n品相：极佳，不过有些使用痕迹\n备注：治疗师们似乎很喜欢它；他得赶紧赎回，否则我们就卖给别人了\n典当人：拾荒者拜尔德，就是住在拉希姆旁边的那只青蛙。\n借款：300金币\n赎回期限：霜落月24日"

    old "7. {b}Steel Dagger{/b}\nCondition: Excellent, pristine even.\nNote: Straight out of the anvil, looks good.\nPawned by: Pickard the blacksmith, he never redeems his weapon, should've just sold them\nLoan Amount: 55 Gold\nRedemption Due Date: 12th of Suncrest\n\n8. {b}Sapphire Necklace of Vitality{/b}\nCondition: Excellent\nNote: says it's gilded with pure gold, but it's not reflective enough, not sure if it's real, gotta need an appraiser like Gwyd\nPawned by: Hooded guy, can't hear half of what he says\nLoan Amount: 120 Gold\nRedemption Due Date: 30th of Frostfall"
    new "7. {b}钢制匕首{/b}\n品相：极佳，甚至可以说完好无损。\n备注：刚出铁砧，看起来不错。\n典当人：铁匠皮卡德。他从来不赎回自己的武器，早知道直接卖了。\n借款：55金币\n赎回期限：日辉月12日\n\n8. {b}活力蓝宝石项链{/b}\n品相：极佳\n备注：据说镀的是纯金，但反光不够，我不确定是真是假。得找像格威德这样的鉴定师才行。\n典当人：戴兜帽的家伙，根本听不清他说的一半话。\n借款：120金币\n赎回期限：霜落月30日"

    old "9. {b}Likkathian Iron Helmet{/b}\nCondition: Excellent, the seller should put it on himself\nNote: Nah\nPurchased by: duh\nSale Price: 3000 gold\n\n10. {b}Ring of Eldest{/b}\nCondition: Excellent, it sounds just as cheesy as it should\nNote: Not to be confused with another ring, this one is cosmetic only, referenced by the northern supplier\nTraded for: Crystal Orb of Mending, gotta say sorry to Baird."
    new "9. {b}利卡希亚铁盔{/b}\n品相：极佳，卖家应该自己戴上它\n备注：没什么好说的\n买家：呃，随便吧\n售价：3000金币\n\n10. {b}长老之戒{/b}\n品相：极佳，听起来就该这么俗气\n备注：不要和另一枚戒指混淆；这枚只有装饰作用，是北方供应商提到的那一枚\n换得：修复水晶球，得跟拜尔德说声抱歉。"

    old "11. {b}Elixir of Fleeting Agility{/b}\nCondition: Excellent, never opened before.\nNote: Seems to be a rip-off of Haskie's old recipe, looks good though.\nSold by: Andri the travelling merchant\nPurchase Price: 60 Gold\n\n12. {b}Rock Sculpture of Tapjoo{/b}\nCondition: Excellent, small crack in the bottom\nNote: Seller refused to elaborate on the origin but this is real old, matches Tapjoo's mask in other goat painting so it's legit\nSold by: Another Hooded guy, with horn this time.\nPurchase Amount: 2150 Gold"
    new "11. {b}稍纵即逝的敏捷药剂{/b}\n品相：极佳，从未开封。\n备注：似乎是哈斯基旧配方的仿制品，不过看起来不错。\n卖家：旅行商人安德里\n购入价：60金币\n\n12. {b}塔普久岩雕{/b}\n品相：极佳，底部有一道小裂缝\n备注：卖家拒绝说明来源，但这东西真的很古老；它和其他山羊画作中的塔普久面具相符，所以是真的\n卖家：另一个戴兜帽的家伙，这次还长着角。\n购入价：2150金币"

    old "13. {b}Old Bronze-plated Armor{/b}\nCondition: Excellent\nNote: it was pretty lame, get it Ole? Lame? \nPawned by: Ludvar the wolf, he keeps bugging me about the price\nLoan Amount: 301 gold\nRedemption Due Date: Negotiable\n\n14. {b}Copy of the History of Otsovaara{/b}\nCondition: Excellent?\nNote: Sturdy paper, clean handwriting but too modern for any scholar with self-respect. \nSale Price: 40 Gold"
    new "13. {b}旧式青铜板甲{/b}\n品相：极佳\n备注：它挺“差劲”的，懂吗欧勒？差劲？\n典当人：狼族路德瓦尔，他一直缠着我问价格\n借款：301金币\n赎回期限：可协商\n\n14. {b}《奥察瓦拉史》副本{/b}\n品相：极佳？\n备注：纸张结实，字迹工整，但对任何有自尊的学者来说都太现代了。\n售价：40金币"

    old "15. {b}12 pieces of Werewolf Pelts{/b}\nCondition: Excellent, freshly harvested.\nNote: The hunters are on their hunt again, will pass this to Rahim later, {i}no werewolves involved are hurt during this process, I think.{/i}\nSold by: Est the leader\nPurchase Price: 240 Gold\n\n"
    new "15. {b}12张狼人皮{/b}\n品相：极佳，刚刚剥下。\n备注：猎人们又出发狩猎了，之后会把它交给拉希姆；{i}我想，这个过程中没有狼人受伤。{/i}\n卖家：首领埃斯特\n购入价：240金币\n\n"

    old "Moss\nAn unusual occurrence today has piqued my curiosity. While overseeing routine maintenance in the longhouse, I noticed a faint draft emanating from behind the old tapestry of the harvest. It's strange, considering that wall has no doors or windows. On closer inspection, I found a hidden seam in the wooden paneling. Armed with a lantern and a sense of intrigue, I ventured down the steps. The air grew cooler, carrying the scent of damp earth and aged stone. At the bottom, I discovered a small chamber with walls adorned in faded symbols and carvings — figures cloaked and hooded, holding staffs, and intricate patterns resembling flowing water or the river itself."
    new "苔藓\n今天发生了一件不同寻常的事，勾起了我的好奇心。我在长屋监督例行维护时，注意到丰收旧挂毯后方传来一缕微风。考虑到那面墙既没有门也没有窗，这很奇怪。仔细检查后，我在木板上发现了一道隐藏的接缝。我提着灯笼，怀着探究的心情走下台阶。空气渐冷，带着湿土和古老石头的气味。最底下是一间小室，墙上装饰着褪色的符号与雕刻——一个个披袍戴帽、手持法杖的人影，以及仿佛流水或河流般的复杂纹样。"

    old "In the center stood a simple stone mural, unadorned yet commanding. The atmosphere was thick with an indefinable weight, as if the room itself was holding its breath. I felt an inexplicable pull, a whisper at the edge of consciousness urging me to delve deeper. I attempted to discuss with Irm, the steward, hoping he might shed some light on its origin. He seemed genuinely puzzled, assuring me that no records mention any subterranean structures beneath the longhouse. Sleep did not come easily tonight. My dreams were vivid — a dense forest bathed in silver moonlight, shadows stretching and twisting among the trees. Amidst the darkness, a pair of orange, luminous eyes watched me intently. I awoke unsettled but oddly compelled to return to the hidden chamber."
    new "中央立着一幅朴素的石制壁画，没有装饰，却自有威严。空气中弥漫着难以言明的沉重，仿佛房间本身屏住了呼吸。一股无法解释的牵引感在意识边缘低语，催促我继续深入。我试着和管事伊尔姆谈论此事，希望他能解释它的来历。他似乎真的感到困惑，向我保证没有任何记录提到长屋下方存在地下结构。今晚我很难入睡。梦境清晰得可怕——一片沐浴在银色月光中的密林，树间的影子伸展、扭曲。黑暗中，一双橙色的发光眼睛紧紧盯着我。我不安地醒来，却奇怪地想要回到那间隐秘的小室。"

    old "Shepherd\nSeveral days have passed since my initial descent, and the hidden depths beneath the longhouse occupy my every thought. Each evening, under the guise of extended duties, I return to explore further. The chamber I first discovered is but an antechamber to a more extensive network of rooms and passageways. As I navigate this labyrinth, I find that the walls themselves seem alive with meaning. The symbols and carvings, once obscure, begin to form patterns—repeating motifs of Tapjoo's staff. There are depictions of figures following the old god, their faces indistinct but their postures reverent. The puzzles I encounter are intricate yet intuitive, as if designed to be solved by a specific person or type of person."
    new "牧羊人\n自从第一次下到地下以来，已经过去了好几天。长屋下的隐秘深处占据了我的全部思绪。每天傍晚，我都以公务未完为借口回来继续探索。我最初发现的房间只是更大房间与通道网络的前室。穿行在这座迷宫中时，我发现墙壁本身仿佛充满了意义。那些曾经晦涩的符号与雕刻开始组成图案——反复出现的塔普久法杖纹样。墙上描绘着追随旧神的人影，他们的面孔模糊，姿态却充满敬意。我遇到的谜题精巧而直观，仿佛是专为某一个人，或某一类人设计的。"

    old "Stone doors yield to pressure applied in certain sequences, and pathways open when patterns are traced upon the walls. My conversations with the steward grow strained. He remarks on my frequent absences from communal gatherings. I offer vague explanations about clerical duties and village records, but I sense his growing concern. The eyes in the forest have become a recurring presence, watching me with what feels like expectation. Last night, the dream changed. The eyes drew closer, and I could make out a figure — a shepherd cloaked in shadows, holding a staff that glinted in the moonlight. He extended his hand as if inviting me to follow. I awoke with a start, the image seared into my mind, and my horns ached greatly."
    new "石门会在按特定顺序施加压力后开启，沿着墙壁描画图案也会使通路显现。我和管事的谈话越来越紧张。他注意到我经常缺席集会，我便用处理文书和村庄记录等含糊的理由搪塞，但能感觉到他的担忧正在加深。森林中的那些眼睛已经成为反复出现的存在，用仿佛期待什么的目光注视着我。昨晚，梦境变了。那些眼睛靠得更近，我看清了一个身影——一个披着阴影、手持法杖的牧羊人，法杖在月光下闪闪发亮。他伸出手，仿佛邀请我跟随。我猛然惊醒，画面像烙印一样留在脑海中，双角也剧烈疼痛。"

    old "Horns\nTime has become fluid. Days blend into nights without distinction. I find myself losing hours, emerging from the depths to find the sun setting when I thought it had just risen. The temple—there is no other word for it—has a hold on me that I cannot break, nor am I certain I want to. I've begun to piece together more of the inscriptions - {i}Only those who bear the sacred crowns of nature shall hear Tapjoo's whispers. Through the horns that touch the sky, his wisdom flow like rivers unseen.{/i} Almost immediately I touched my horns, it feels warmer than any other part of my body. I can't help but feel that I am retracing their steps."
    new "角\n时间变得不再流动。白昼与黑夜混在一起，毫无分别。我发现自己不断失去几个小时的时间；从深处出来时，明明以为太阳才刚升起，却发现它已经西沉。那座神殿——除此之外我找不到别的称呼——牢牢抓住了我，我无法挣脱，也不确定自己是否想挣脱。我开始拼凑出更多铭文的内容：{i}只有戴着自然神圣冠冕的人，才能听见塔普久的低语。透过触及天穹的双角，他的智慧如无形之河般流淌。{/i}我几乎立刻摸了摸自己的角，那里比身体其他部位都温暖。我无法摆脱一种感觉：自己正在重走他们走过的路。"

    old "The challenges, the symbols, the pervasive presence of the old god — all seem tailored to lead me toward some revelation. Yet, doubt gnaws at me. Is this a path to wisdom, or am I being led astray by forces I do not understand? The steward's concern has turned to suspicion. He mentioned rumors circulating among the villagers — whispers of strange lights seen in the longhouse at odd hours, of the mayor neglecting his duties. I attempted to allay his fears, but I sense a growing rift. The eyes haunt me still, no longer confined to dreams. In the forest beyond the village, I feel their gaze upon me. During council meetings, I catch reflections in the window that do not match the room. The line between reality and illusion is blurring."
    new "这些挑战、符号，以及旧神无处不在的存在，似乎都被精心安排来引导我走向某个启示。然而疑虑啃噬着我。这究竟是通往智慧的道路，还是我正被无法理解的力量引入歧途？管事的担忧转为怀疑。他提到村民间流传的传闻——有人在奇怪的时辰看见长屋亮起异光，还说市长疏于履职。我试图消除他的恐惧，却感觉裂痕正在扩大。那些眼睛依然纠缠着我，不再局限于梦中。在村外的森林里，我能感到它们的注视。议会开会时，我会在窗中捕捉到与房间不相称的倒影。现实与幻觉之间的界线正在模糊。"

    old "Altar\nThis may be my final entry. I stand at a precipice. The temple's final chamber lies before me, its entrance sealed by a complex mechanism that requires not just physical keys but an alignment of symbols and, I suspect, intent. I've gathered the artifacts found throughout the temple—a set of engraved stones, each bearing a unique symbol. Arranging them in what I believe to be the correct configuration, the door began to open, but stopped short. It seems there's one piece missing, or perhaps a final act required of me that I have yet to discern. The steward confronted me today with an ultimatum. He demands that I refocus on my responsibilities or consider stepping down."
    new "祭坛\n这可能是我最后的记录。我站在悬崖边。神殿的最终房间就在眼前，入口被复杂的机关封闭；它不只需要实体钥匙，还需要符号的排列，而且我怀疑，还需要意志。我收集了神殿各处找到的遗物——一组刻着独特符号的石头。我按照自认为正确的方式排列它们，门开始开启，却在中途停住。似乎少了一件东西，或者还需要某个我尚未察觉的最后行动。管事今天来找我摊牌，给了我最后通牒。他要求我重新专注于职责，否则就考虑辞职。"

    old "He speaks of the welfare of the village, the trust placed in me. His words are reasonable, but they feel distant, as if coming from another world. That night, the dreams returned with a vengeance. The eyes were closer than ever, the shepherd's figure looming. This time, he spoke — a single phrase that echoed in my mind even after waking: 'The shepherd comes for us all.' I don't know what it means, but it fills me with equal parts dread and anticipation. I leave this journal behind for whoever may find it. Perhaps the steward, perhaps another drawn by the temple's allure. My path leads elsewhere now. I will enter the final chamber tomorrow, with or without the missing piece."
    new "他谈到村庄的福祉，以及村民对我的信任。他的话合情合理，却让人感到遥远，仿佛来自另一个世界。那天夜里，梦境报复般卷土重来。那些眼睛比以往更近，牧羊人的身影高高压来。这一次，他开口了——一句即使醒来后仍在我脑中回响的话：“牧羊人会来找我们所有人。”我不知道这是什么意思，却同时感到恐惧与期待。我把这本日记留给将来找到它的人。也许是管事，也许是另一个被神殿魅力吸引的人。我的道路如今通向别处。明天，无论缺不缺那件遗失之物，我都要进入最终房间。"

    old "Dragon\nToday, before my search for answers, I stumbled upon an ancient parchment hidden within a concealed compartment in one of the temple's outer chambers. The parchment is fragile, its edges crumbling at the touch, but the ink remains legible. It appears to be a prophecy or perhaps a warning. It speaks of a horned dragon that slumbers beneath the earth, bound by chains forged of forgotten oaths. The dragon is said to awaken when the shepherd's call reaches the depths, heralding a time of upheaval and transformation. I can't help but wonder if this prophecy is connected to the chamber I cannot yet access. Is the horned dragon a metaphor, or does something more literal lie beneath the temple? The idea both fascinates and unsettles me."
    new "龙\n今天，在寻找答案之前，我在神殿外殿的一间隐秘房间里偶然发现了一张藏起来的古老羊皮纸。羊皮纸十分脆弱，边缘一碰就碎，但墨迹仍然清晰可读。它看起来像预言，也可能是一则警告。上面说，一条长角的龙沉睡在大地之下，被遗忘誓言铸成的锁链束缚。传说当牧羊人的呼唤抵达深处时，龙便会苏醒，宣告动荡与蜕变的时代。我不禁怀疑，这则预言是否与那间我尚未进入的房间有关。长角的龙只是隐喻，还是神殿下面真的藏着某种更具体的东西？这个念头既令我着迷，也让我不安。"

    old "The search has drained my entire body unto exhaustion, my will dwindles but my determination unchanged. I had decided to rest before my final search commences at night. I only dread meeting the shepherd again, his words did not stop resonating in my mind. May the old gods watch over me."
    new "这场搜寻把我的身体彻底耗到精疲力竭，意志正在衰弱，但决心没有改变。我决定在夜里的最后一次搜寻开始前先休息。唯独想到要再次见到牧羊人，我便感到恐惧；他的话仍不断在脑中回响。愿旧神注视着我。"

    old "Day 1214\nAin't we just the luckiest sons of benches? We've been robbin' folks left and right, and our coffers are brimming with shiny bits and bobs. Here's what we've got to show for it:\n\n10 flowin' robes of silk. We'll probably sell these to some rich fool in the city who's willing to pay through the nose for some fancy cloth.\nA roll of paper, Looka told us it's an old poem about some hero and monster, forgot what he said. We took it from that bard who's been making noise outside, should fetch a good price with it.\nThink we've got like, whole lotta gold tradin some goods, Buck's gonna get us some good wine today."
    new "第1214日\n我们不是走了大运吗，几位凳子家的好儿子？我们一直在四处抢劫，钱箱里塞满了闪亮的零碎。看看我们的战果：\n\n10件流光丝袍。我们大概能把它卖给城里某个愿意为华贵布料大把掏钱的有钱蠢货。\n一卷纸。卢卡说那是一首讲英雄与怪物的古诗，具体说了什么我忘了。我们从外面那个吵个不停的吟游诗人手里拿来，应该能卖个好价钱。\n我们好像用这些货物换了很多金币，巴克今天要给我们弄些好酒。"

    old "Day 1215\nWe had ourselves a real good time the other night. We got drunk on wine and told stories of our exploits. \nSpeaking of selling things, we managed to offload that piece of paper from the bard to a fence we know in the village. Got a good price for it too. 3000 gold right in our pocket.\n\nWe took some other stuff also:\n25 pieces of iron ore, think some werewolves came out of nowhere and delivered them right at our doorstep.\n1 magical wand, swiped from a traveling wizard. We're not sure what to do with this yet, so we'll hold on to it for a bit."
    new "第1215日\n前几晚我们过得真痛快。我们喝醉了酒，讲着自己的战绩。\n说到卖东西，我们成功把那张从吟游诗人手里拿来的纸卖给了村里认识的销赃人。价格也不错，足足3000金币进了我们的口袋。\n\n我们还拿到了一些别的东西：\n25块铁矿石，好像是几只狼人突然出现，把它们直接送到了我们门口。\n1根魔杖，从一位旅行巫师那里顺手牵羊来的。我们还不知道该拿它怎么办，所以先留一阵子。"
