# The book screen receives these pages as runtime data, so they need explicit
# string entries in addition to the ordinary dialogue translation blocks.

translate schinese_rewrite strings:

    old "{b}The Somni-Etern{/b} is a dangerous mushroom for the untrained forager. Its soporific effects are strong enough that a full bite will shut down your nervous system.\nThere have been few cases of survivors - all of them having consumed smaller amounts previously. I assume they built a resistance to it; more on that later.\nDespite the deadly nature of the somni-etern, it is incredibly useful to the medicinal practitioner.\nMixing only a bit in- - —-----d soup or drink, and feeding the result to a patient, will ease their pain significantly. It also tastes quite good, from —- I — —-"
    new "{b}永恒梦魇{/b}对未经训练的采集者来说十分危险。它的催眠作用强烈到足以让你咬下一大口后神经系统停止运作。\n幸存者寥寥无几——而且他们此前都只摄入过少量。我猜，他们因此产生了抗性；后面再详谈。\n尽管永恒梦魇具有致命性，却对医术从业者极其有用。\n只需在汤或饮品中加入一点，再将成品喂给病人，就能大幅缓解他们的疼痛。味道也相当不错——至少我是这么认为的。"

    old "Caution in determining dosage is, of course, critical. Quite p--ibly more important, however, is that patients can and will grow resistant, and/or addicted.\nI unfortunately l—--d t- har- w-. M- -on of-e- suf-re- fr- night terrors. To sol-e this, I -xe- som—--rn into h- baby formula ev-y nig-t.\nSome-ow, he fa—d to gr-w addicted. He is, h-ev-r, co-ple-ly im-ne to the mushrooms.\n-- -s six n-w, fi- yea- ol-e- t— he -as then. Perhaps it was my occas-nal -xp-iments on the s-je- that led t- h- im-un-y being perma-nt, or at le— not reduced at all in five years.\n-- - —-- mentioning that - — been t—- months sin-e I — — —-.\nI do not want him to watch me die."
    new "谨慎确定剂量当然至关重要。不过，更重要的或许是，患者能够、也确实会产生抗性，和／或上瘾。\n我不幸是吃了苦头才明白这一点。我儿子经常遭受夜惊。为了解决这个问题，我每晚都往他的婴儿奶粉里混入一些东西。\n不知怎么的，他没有因此上瘾。不过，他对这种蘑菇完全免疫。\n他现在六岁了，比当时大了五岁。也许是我偶尔在这方面做的实验，才让他的免疫力永久存在，或者至少五年来完全没有减弱。\n——还得提一句，自从我……以来，已经过去了……个月。\n我不想让他看着我死去。"

    old "\n\n\n\n\n\n\n\n                Battle of Lusterfield\n"
    new "\n\n\n\n\n\n\n\n卢斯特菲尔德之战\n"

    old "\n\n\n\n\nIhktn the annals of history, few tales are as poignant as the conflict between the peaceful village of Lusterfield and the proud Kechioeren tribe. This book aims to preserve the memory of the events that led from friendship to ferocious battle, as a part of the history and culture of Mokken as a whole."
    new "\n\n\n\n\n在历史编年史中，很少有故事能像和平的卢斯特菲尔德村与骄傲的凯奇欧伦部族之间的冲突那样令人痛心。本书旨在保存那段由友谊走向惨烈战斗的往事，作为整个莫肯历史与文化的一部分。"

    old "Lusterfield, nestled in the verdant embrace of gentle hills, had long been a beacon of peace and prosperity. Battle and wars are rarity, if not non-existent, hence the reason no one has been pronounced the Mayor of Lusterfield for decades. Its people lived in harmonious trade with the Kechioeren, a tribe renowned for their mana-rich flowing water and its close ties with the primordial runes. Season after season, the village square buzzed with the exchange of goods from both communities. The Goat Tribe brought wools, water, intricately mined crystals, while Lusterfield offered grains, textiles, and crafted beers. It was a partnership built on mutual respect and benefit.\n\n"
    new "卢斯特菲尔德坐落在苍翠葱郁的和缓群山之间，长久以来一直是和平与繁荣的灯塔。这里鲜有战斗与战争，甚至可以说几乎从未发生过，因此数十年来都无人被任命为卢斯特菲尔德的镇长。镇民与凯奇欧伦人和谐贸易；这个部族以蕴含丰富魔力的流动水源以及与原初符文的紧密联系而闻名。一季又一季，村镇广场上总是充满了两方社区交换货物的喧闹声。山羊部落带来羊毛、水和精心开采的水晶，而卢斯特菲尔德则提供谷物、纺织品和酿制的啤酒。这是一段建立在相互尊重与互惠互利之上的合作关系。\n\n"

    old "The turning point came unexpectedly during one morning when a goat wagon, heavy with trade goods bound for Lusterfield, was ambushed.\n\nThe assailants were never seen, leaving no trace of their identity, but the carnage spoke of a deliberate act to incite fury. Lives were lost, and treasures plundered, and almost at the same time, the Primordial runes at the high mountain was stolen mysteriously. Despite Lusterfield's protests of innocence, the seeds of distrust were sown in blood-soaked soil.\n\nTevfik, the stalwart leader of the goats, consumed by grief and the cries for justice"
    new "转折点在某个清晨猝然降临：一辆满载着运往卢斯特菲尔德的贸易货物的山羊族货车遭到了伏击。\n\n袭击者始终不见踪影，也没有留下任何能证明其身份的痕迹，但惨状却表明，这是一场蓄意煽动众怒的行动。有人丧生，财宝遭到掠夺，几乎就在同一时间，高山上的原初符文也神秘失窃。尽管卢斯特菲尔德一再抗辩、声明自身清白，猜疑的种子还是被播撒在了血染的土地上。\n\n山羊族坚毅的首领特夫菲克沉浸在悲痛之中，耳边回荡着族人对正义的呼声"

    old " for his people, he pointed his fingers at Lusterfield. War cries echoed through the hills as Tevfik led his warriors in a vengeful strike against the village.\n\nTevfik and his fighters quickly surrounded the village with their camps, threatening to capture their supposed leader, Rahim. The Lusterfolks, unprepared for the ferocity and feeling the sting of betrayal, scrambled to defend their homes and families.\n\nBattle after battle, neither side gained ground. The goats, fierce but few, and the villagers, resolute yet unskilled in the ways of war, found themselves locked in a stalemate that threatened to drag on until both were but memories in the wind.\n\nDespite the violent battle, only few lives were lost, the reluctance of both side's soldiers remains strong."
    new "为了他的族人，他将矛头指向了卢斯特菲尔德。特夫菲克率领战士们向村庄发起复仇突袭，山间回荡着战争的呐喊。\n\n特夫菲克和他的战士们很快扎营包围了村庄，威胁要抓住他们认定的首领雷希姆。卢斯特菲尔德人没料到对方会如此凶猛，又感受到了背叛的刺痛，只得慌忙保卫自己的家园与家人。\n\n一场又一场战斗下来，双方都未能推进半步。凶猛却为数不多的山羊，与意志坚定却不谙战事的村民陷入了僵局，这场战争仿佛注定会一直拖延下去，直到双方都只剩风中的记忆。\n\n尽管战况惨烈，丧生者却寥寥无几，而双方士兵对于继续厮杀的抗拒依然强烈。"

    old "However, Tevfik did not retreat, the leader was not known for his indolence, many buildings of the village crumbled under the goat's magic, as the battle continues.\n\nAfter the dawn, a shadow moved through the night. Lothar Faelon, an adventurer who lived in Lusterfield seeking solace from his own battles, could not stand idly by. Armed with little more than his wits and a keen blade, he infiltrated the Kechioeren camp under the cover of darkness. It's not known the details of his attempt. Only that he eventually found Tevfik, weary and exposed. The confrontation was swift, a silent struggle that ended with the leader's fall."
    new "然而，特夫菲克并未退却，这位首领可不是以懒散闻名；战斗仍在继续，村中许多建筑在山羊魔法的作用下坍塌。\n\n黎明之后，一道身影悄无声息地穿过夜色。洛萨尔·费伦是一名住在卢斯特菲尔德、试图从自己的战斗中寻求慰藉的冒险者，他无法袖手旁观。他几乎只凭机智与一把锋利的刀刃，在夜色掩护下潜入了凯奇欧伦营地。他此次行动的细节无人知晓，只知道他最终找到了疲惫且毫无防备的特夫菲克。双方迅速交锋，这场无声的搏斗以首领倒下告终。"

    old "Lothar disappeared into the night as quietly as he had come, leaving a leaderless tribe to grapple with the reality of their loss.\n\nWith Tevfik gone, the battle's fever broke. The goats, leaderless and confused, retreated, their will to fight sapped by their leader's untimedly demise. Lusterfield mourned its dead but also breathed a sigh of relief. Lothar, known to the villagers only as a mysterious benefactor, became a legend whispered in awe.\n\nPeace was restored between the both sides, but destruction remains permanent, the broken bridge inbetween was never repaired, haunted by the shadows of what had been lost between them."
    new "洛萨尔悄无声息地消失在夜色中，正如他悄无声息地到来，只留下一个失去首领的部族去面对失去首领的现实。\n\n特夫菲克死后，战场上的狂热随之消退。山羊人群龙无首、茫然无措地撤退了，他们的战意被首领突如其来的死亡消磨殆尽。卢斯特菲尔德为死者哀悼，同时也松了一口气。村民只知道洛萨尔是一位神秘的援助者，他成了一个令人敬畏、被人低声传颂的传奇。\n\n双方恢复了和平，但毁灭却永久留存。那座断桥始终无人修复，失去的一切留下的阴影依旧萦绕其间。"

    old "With this in mind, the mystery of primordial runes remained unsolved, Furkan, son of Tevfik, succeeded as the new chief of the goats. Memorials were erected on both sides, not just for the fallen, but for the friendship that had once blossomed."
    new "有鉴于此，原初符文的谜团仍未解开。特夫菲克之子弗坎继任为山羊人的新首领。双方都立起了纪念碑，不仅为了悼念死者，也为了纪念那段曾经萌芽的友谊。"
