# The book screen receives these pages as runtime data, so they need explicit
# string entries in addition to the ordinary dialogue translation blocks.

translate schinese_rewrite strings:

    old "{b}The Somni-Etern{/b} is a dangerous mushroom for the untrained forager. Its soporific effects are strong enough that a full bite will shut down your nervous system.\nThere have been few cases of survivors - all of them having consumed smaller amounts previously. I assume they built a resistance to it; more on that later.\nDespite the deadly nature of the somni-etern, it is incredibly useful to the medicinal practitioner.\nMixing only a bit in- - —-----d soup or drink, and feeding the result to a patient, will ease their pain significantly. It also tastes quite good, from —- I — —-"
    new "{b}永眠菇{/b}对未经训练的采集者来说十分危险。它的催眠作用强烈到足以让一整口蘑菇使你的神经系统停摆。\n幸存者寥寥无几，而且他们此前都只食用过少量。我猜那让他们产生了抗性；后面再详谈。\n尽管永眠菇致命，它对药剂师却极其有用。\n只需在汤或饮品中加入一点，再把成品喂给病人，就能大幅缓解疼痛。味道也相当不错——至少我是这么认为的。"

    old "Caution in determining dosage is, of course, critical. Quite p--ibly more important, however, is that patients can and will grow resistant, and/or addicted.\nI unfortunately l—--d t- har- w-. M- -on of-e- suf-re- fr- night terrors. To sol-e this, I -xe- som—--rn into h- baby formula ev-y nig-t.\nSome-ow, he fa—d to gr-w addicted. He is, h-ev-r, co-ple-ly im-ne to the mushrooms.\n-- -s six n-w, fi- yea- ol-e- t— he -as then. Perhaps it was my occas-nal -xp-iments on the s-je- that led t- h- im-un-y being perma-nt, or at le— not reduced at all in five years.\n-- - —-- mentioning that - — been t—- months sin-e I — — —-.\nI do not want him to watch me die."
    new "当然，判断用量时必须格外谨慎。然而更重要的是，病人确实会逐渐产生抗性，甚至上瘾。\n很遗憾，我没能……我儿子曾饱受夜惊折磨。为了解决这个问题，我每天晚上都往他的婴儿配方里加入一点永眠菇。\n不知怎么的，他没有上瘾。不过，他对这种蘑菇完全免疫。\n那孩子如今已经六岁，而五年前他还只有一岁。也许正是我偶尔进行的实验，让他的免疫力永久形成，至少五年来从未减弱。\n——我不想提起，距离我……已经过去三个月了。\n我不想让他看着我死去。"

    old "\n\n\n\n\n\n\n\n                Battle of Lusterfield\n"
    new "\n\n\n\n\n\n\n\n                卢斯特菲尔德之战\n"

    old "\n\n\n\n\nIhktn the annals of history, few tales are as poignant as the conflict between the peaceful village of Lusterfield and the proud Kechioeren tribe. This book aims to preserve the memory of the events that led from friendship to ferocious battle, as a part of the history and culture of Mokken as a whole."
    new "\n\n\n\n\n在史册中，很少有故事像和平的卢斯特菲尔德村与骄傲的凯奇奥伦部落之间的冲突这样令人唏嘘。这本书旨在保存那段从友谊走向惨烈战争的历史，也记录莫肯整体历史与文化的一部分。"

    old "Lusterfield, nestled in the verdant embrace of gentle hills, had long been a beacon of peace and prosperity. Battle and wars are rarity, if not non-existent, hence the reason no one has been pronounced the Mayor of Lusterfield for decades. Its people lived in harmonious trade with the Kechioeren, a tribe renowned for their mana-rich flowing water and its close ties with the primordial runes. Season after season, the village square buzzed with the exchange of goods from both communities. The Goat Tribe brought wools, water, intricately mined crystals, while Lusterfield offered grains, textiles, and crafted beers. It was a partnership built on mutual respect and benefit.\n\n"
    new "卢斯特菲尔德坐落在青翠山丘的怀抱中，长久以来一直是和平与富足的灯塔。这里几乎从未发生过战争，因此数十年来都没有人被宣布为卢斯特菲尔德的市长。村民与凯奇奥伦和谐贸易；那个部落以富含法力的流水以及与原初符文的紧密联系闻名。年复一年，村广场上都回荡着两个群体交换货物的喧闹声。山羊部落带来羊毛、水和精心开采的水晶，卢斯特菲尔德则提供谷物、纺织品和酿造的啤酒。这是一段建立在相互尊重与互惠基础上的合作。\n\n"

    old "The turning point came unexpectedly during one morning when a goat wagon, heavy with trade goods bound for Lusterfield, was ambushed.\n\nThe assailants were never seen, leaving no trace of their identity, but the carnage spoke of a deliberate act to incite fury. Lives were lost, and treasures plundered, and almost at the same time, the Primordial runes at the high mountain was stolen mysteriously. Despite Lusterfield's protests of innocence, the seeds of distrust were sown in blood-soaked soil.\n\nTevfik, the stalwart leader of the goats, consumed by grief and the cries for justice"
    new "转折来得出人意料。某天清晨，一辆载满、正要前往卢斯特菲尔德的贸易货物的山羊车遭到了伏击。\n\n袭击者始终没有现身，也没有留下任何身份线索，但满地的惨状足以说明这是一场蓄意煽动怒火的行动。有人丧命，财宝被掠夺；几乎与此同时，高山上的原初符文也神秘失窃。尽管卢斯特菲尔德极力申辩自己无辜，不信任的种子仍被播进了血染的土地。\n\n山羊的坚毅领袖特夫菲克被悲痛与族人追求正义的呼声吞没，"

    old " for his people, he pointed his fingers at Lusterfield. War cries echoed through the hills as Tevfik led his warriors in a vengeful strike against the village.\n\nTevfik and his fighters quickly surrounded the village with their camps, threatening to capture their supposed leader, Rahim. The Lusterfolks, unprepared for the ferocity and feeling the sting of betrayal, scrambled to defend their homes and families.\n\nBattle after battle, neither side gained ground. The goats, fierce but few, and the villagers, resolute yet unskilled in the ways of war, found themselves locked in a stalemate that threatened to drag on until both were but memories in the wind.\n\nDespite the violent battle, only few lives were lost, the reluctance of both side's soldiers remains strong."
    new "他把矛头指向了卢斯特菲尔德。特夫菲克率领战士复仇袭击村庄，战吼在群山间回荡。\n\n特夫菲克与战士们迅速扎营包围村庄，扬言要抓住他们认定的领袖拉希姆。卢斯特民没料到山羊会如此凶猛，又饱尝背叛的刺痛，只得慌忙保护自己的家园与家人。\n\n一场又一场战斗过去，双方都没有取得进展。山羊凶悍却人数稀少，村民意志坚定却不谙战法；他们陷入了僵局，仿佛战事会一直拖延，直到双方都只剩风中的回忆。\n\n尽管战斗惨烈，真正丧生的人并不多；双方士兵都仍强烈地不愿继续互相残杀。"

    old "However, Tevfik did not retreat, the leader was not known for his indolence, many buildings of the village crumbled under the goat's magic, as the battle continues.\n\nAfter the dawn, a shadow moved through the night. Lothar Faelon, an adventurer who lived in Lusterfield seeking solace from his own battles, could not stand idly by. Armed with little more than his wits and a keen blade, he infiltrated the Kechioeren camp under the cover of darkness. It's not known the details of his attempt. Only that he eventually found Tevfik, weary and exposed. The confrontation was swift, a silent struggle that ended with the leader's fall."
    new "然而特夫菲克没有撤退；这位领袖从不懒怠。战斗继续之时，村中许多建筑在山羊的魔法下坍塌。\n\n黎明之后，一道身影穿过黑夜。洛萨·费隆是一名住在卢斯特菲尔德、试图从自己的战斗中寻求慰藉的冒险者，他无法袖手旁观。他手中除了机智与一把锋利的刀刃几乎一无所有，却仍借着夜色潜入凯奇奥伦营地。没人知道那次行动的细节，只知道他最终找到了疲惫而毫无防备的特夫菲克。交锋来得迅疾，是一场无声的搏斗，最终以这位领袖倒下告终。"

    old "Lothar disappeared into the night as quietly as he had come, leaving a leaderless tribe to grapple with the reality of their loss.\n\nWith Tevfik gone, the battle's fever broke. The goats, leaderless and confused, retreated, their will to fight sapped by their leader's untimedly demise. Lusterfield mourned its dead but also breathed a sigh of relief. Lothar, known to the villagers only as a mysterious benefactor, became a legend whispered in awe.\n\nPeace was restored between the both sides, but destruction remains permanent, the broken bridge inbetween was never repaired, haunted by the shadows of what had been lost between them."
    new "洛萨来时悄无声息，离去时也消失在夜色中，只留下一个失去首领的部落去面对他们的损失。\n\n特夫菲克死后，战事的狂热逐渐消退。山羊失去领袖、陷入混乱，只能撤退；首领不合时宜的死亡耗尽了他们的战意。卢斯特菲尔德哀悼死者，也终于松了一口气。村民只把洛萨当作神秘的恩人，他的名字在敬畏的低语中成了传说。\n\n双方恢复了和平，但毁坏却永远留了下来。那座破桥始终没有修复，仿佛被两边失去的一切的阴影纠缠。"

    old "With this in mind, the mystery of primordial runes remained unsolved, Furkan, son of Tevfik, succeeded as the new chief of the goats. Memorials were erected on both sides, not just for the fallen, but for the friendship that had once blossomed."
    new "尽管如此，原初符文的谜团仍未解开。特夫菲克之子福坎继任山羊的新任酋长。双方都立起了纪念碑，纪念的不只是死者，也纪念那段曾经绽放过的友谊。"
