

translate portuguese strings:


    old "Outland Wanderer"
    new "Outland Wanderer"


    old "\n\nOutland Wanderer is a Visual Novel RPG created by f1shsticker.\n\nPlayer plays an outsider stumbling upon the continent of Mokken. In his attempt to travel back to his own Tribe, he bonds and form different relationship with the locals, tackles on unknown forces, and discover shocking yet compelling secret among them. But be ware, your decision will change their lives, forever.\n\nThis is a prototype, aims for laying foundations and systems, storytelling and other elements are not refined yet. A lot of bugs might also exists so there is a very high possibility your save would not be able to transfer to future build.\n\n==========================================================================================================\n\nCredit:\n\nCode/Art/Script: f1shsticker\n\nTranslation:\n\nFont: Adobe Garamond Pro\n\n"
    new "\n\nOutland Wanderer é um RPG Visual Novel criado por f1shsticker.\n\nO jogador interpreta um forasteiro tropeçando no continente de Mokken. Em sua tentativa de viajar de volta para sua própria tribo, ele cria laços e forma um relacionamento diferente com os habitantes locais, enfrenta forças desconhecidas e descobre um segredo chocante e convincente entre eles. Mas cuidado, sua decisão mudará a vida deles, para sempre.\n\nEste é um protótipo, visa estabelecer bases e sistemas, contar histórias e outros elementos ainda não refinados. Muitos bugs também podem existir, então há uma possibilidade muito alta de que seu save não seja capaz de transferir para uma compilação futura.\n\n===================== ================================================== ====================================\n\nCrédito:\n\nCódigo/Arte/Script: f1shsticker\n\nTradução:\n\nFonte: Adobe Garamond Pro\n\n"


translate portuguese strings:


    old "\n\nOutland Wanderer is a Visual Novel RPG created by f1shsticker.\n\nPlayer plays an outsider stumbling upon the continent of Mokken. In his attempt to travel back to his own Tribe, he bonds and form different relationship with the locals, tackles on unknown forces, and discover shocking yet compelling secret among them. But be ware, your decision will change their lives, forever.\n\nThis is a prototype, aims for laying foundations and systems, storytelling and other elements are not refined yet. A lot of bugs might also exists so there is a very high possibility your save would not be able to transfer to future build.\n\n==========================================================================================================\n\n{a=https://discord.gg/QnbJMGhZhV}Official Discord Server{/a}\n\nCredit:\n\nCode/Art/Script:   f1shsticker {a=https://twitter.com/OutlandWanderer}Twitter{/a}\n\nScript: Nyarlothotep {a=https://twitter.com/LoveCountry45}Twitter{/a}\n\nMusic:   Pinewood Jerry  {a=https://twitter.com/Pinewood_Jerry}Twitter{/a}\n\nFrench Translation:  Sannom(Paul)  {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nPortuguese Translation:  Fábio.T\n\nFont: Adobe Garamond Pro\n\n"
    new "\n\nOutland Wanderer é um RPG Visual Novel criado por f1shsticker.\n\nO jogador interpreta um forasteiro tropeçando no continente de Mokken. Em sua tentativa de viajar de volta para sua própria tribo, ele cria laços e forma um relacionamento diferente com os habitantes locais, enfrenta forças desconhecidas e descobre um segredo chocante e convincente entre eles. Mas cuidado, sua decisão mudará a vida deles, para sempre.\n\nEste é um protótipo, visa estabelecer bases e sistemas, contar histórias e outros elementos ainda não refinados. Muitos bugs também podem existir, então há uma possibilidade muito alta de que seu save não seja capaz de transferir para uma compilação futura.\n\n===================== ================================================== ====================================\n\n{a=https://discord.gg /QnbJMGhZhV}Servidor oficial do Discord{/a}\n\nCrédito:\n\nCódigo/Arte/Script: f1shsticker {a=https://twitter.com/OutlandWanderer}Twitter{/a}\n\nScript: Nyarlothotep {a=https://twitter.com/LoveCountry45}Twitter{/a}\n\nMúsica: Pinewood Jerry {a=https://twitter.com/Pinewood_Jerry}Twitter{/a}\n\nTradução em francês: Sannom( Paul) {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nTradução: Fábio.T\n\nFonte: Adobe Garamond Pro\n\n"


translate portuguese strings:


    old "\n\nOutland Wanderer is a Visual Novel RPG created by f1shst icker.\n\nPlayer plays an outsider stumbling upon the continent of Mokken. In his attempt to travel back to his own Tribe, he bonds and form different relationship with the locals, tackles on unknown forces, and discover shocking yet compelling secret among them. But be ware, your decision will change their lives, forever.\n\nThis is a prototype, aims for laying foundations and systems, storytelling and other elements are not refined yet. A lot of bugs might also exists so there is a very high possibility your save would not be able to transfer to future build.\n\n==========================================================================================================\n\n{a=https://discord.gg/QnbJMGhZhV}Official Discord Server{/a}\n\nCredit:\n\nCode/Art/Script:   f1shsticker {a=https://twitter.com/OutlandWanderer}Twitter{/a}\n\nScript: Nyarlothotep {a=https://twitter.com/LoveCountry45}Twitter{/a} {p}\n\nLonelyTree {a=https://discordapp.com/users/273928084388839425}Discord{/a}\n\nMusic:   Pinewood Jerry  {a=https://twitter.com/Pinewood_Jerry}Twitter{/a}\n\nFrench Translation:  Sannom(Paul)  {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nPortuguese Translation:  Fábio.T  {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nFont: Adobe Garamond Pro\n\n"
    new "\n\nOutland Wanderer é um RPG Visual Novel criado por f1shsticker.\n\nO jogador interpreta um forasteiro tropeçando no continente de Mokken. Em sua tentativa de viajar de volta para sua própria tribo, ele cria laços e forma um relacionamento diferente com os habitantes locais, enfrenta forças desconhecidas e descobre um segredo chocante e convincente entre eles. Mas cuidado, sua decisão mudará a vida deles, para sempre.\n\nEste é um protótipo, visa estabelecer bases e sistemas, contar histórias e outros elementos ainda não refinados. Muitos bugs também podem existir, então há uma possibilidade muito alta de que seu save não seja capaz de transferir para uma compilação futura.\n\n===================== ================================================== ====================================\n\n{a=https://discord.gg /QnbJMGhZhV}Servidor oficial do Discord{/a}\n\nCrédito:\n\nCódigo/Arte/Script: f1shsticker {a=https://twitter.com/OutlandWanderer}Twitter{/a}\n\nScript: Nyarlothotep {a=https://twitter.com/LoveCountry45}Twitter{/a} {p}\n\nLonelyTree {a=https://discordapp.com/users/273928084388839425}Discord{/a}\n\nMagnolia\n \nMúsica: Will o Wisp {a=https://soundcloud.com/willowispproductions}Twitter{/a}\n\nPinewood Jerry {a=https://twitter.com/Pinewood_Jerry}Twitter{/a}\n\\ nTradução em francês: Sannom(Paul) {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nTradução em português: Fábio.T {a=https://twitter.com/SannomTigris}Twitter{/ a}\n\nFonte: Adobe Garamond Pro\n\n"



translate portuguese strings:


    old "\n\nOutland Wanderer is a Visual Novel RPG created by f1shsticker.\n\nPlayer plays an outsider stumbling upon the continent of Mokken. In his attempt to travel back to his own Tribe, he bonds and form different relationship with the locals, tackles on unknown forces, and discover shocking yet compelling secret among them. But be ware, your decision will change their lives, forever.\n\nThis is a prototype, aims for laying foundations and systems, storytelling and other elements are not refined yet. A lot of bugs might also exists so there is a very high possibility your save would not be able to transfer to future build.\n\n==========================================================================================================\n\n{a=https://discord.gg/QnbJMGhZhV}Official Discord Server{/a}\n\nCredit:\n\nCode/Art/Script:   f1shsticker {a=https://twitter.com/OutlandWanderer}Twitter{/a}\n\nScript: Nyarlothotep {a=https://twitter.com/LoveCountry45}Twitter{/a} {p}\n\nLonelyTree {a=https://discordapp.com/users/273928084388839425}Discord{/a}\n\nMagnolia\n\nMusic:  Will o Wisp  {a=https://soundcloud.com/willowispproductions}Twitter{/a}\n\nPinewood Jerry  {a=https://twitter.com/Pinewood_Jerry}Twitter{/a}\n\nFrench Translation:  Sannom(Paul)  {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nPortuguese Translation:  Fábio.T  {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nFont: Adobe Garamond Pro\n\n"
    new "\n\nOutland Wanderer é um RPG Visual Novel criado por f1shsticker.\n\nO jogador interpreta um forasteiro aventurando no continente de Mokken. Em sua tentativa de viajar de volta para sua própria tribo, ele cria laços e forma um relacionamento diferente com os habitantes locais, enfrenta forças desconhecidas e descobre um segredo chocante e convincente entre eles. Mas cuidado, sua decisão mudará a vida deles, para sempre.\n\nEste é um protótipo, visa estabelecer bases e sistemas, contar histórias e outros elementos ainda não refinados. Muitos bugs também podem existir, então há uma possibilidade muito alta de que seu save não seja capaz de transferir para uma compilação futura.\n\n===================== ================================================== ====================================\n\n{a=https://discord.gg /QnbJMGhZhV}Servidor oficial do Discord{/a}\n\nCrédito:\n\nCódigo/Arte/Script: f1shsticker {a=https://twitter.com/OutlandWanderer}Twitter{/a}\n\nScript: Nyarlothotep {a=https://twitter.com/LoveCountry45}Twitter{/a} {p}\n\nLonelyTree {a=https://discordapp.com/users/273928084388839425}Discord{/a}\n\nMagnolia\n \nMúsica: Will o Wisp {a=https://soundcloud.com/willowispproductions}Twitter{/a}\n\nPinewood Jerry {a=https://twitter.com/Pinewood_Jerry}Twitter{/a}\n\\ nTradução em francês: Sannom(Paul) {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nTradução em português: Fábio.T {a=https://twitter.com/SannomTigris}Twitter{/ a}\n\nFonte: Adobe Garamond Pro\n\n"
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
