

translate french strings:


    old "Outland Wanderer"
    new "Outland Wanderer"


    old "\n\nOutland Wanderer is a Visual Novel RPG created by f1shsticker.\n\nPlayer plays an outsider stumbling upon the continent of Mokken. In his attempt to travel back to his own Tribe, he bonds and form different relationship with the locals, tackles on unknown forces, and discover shocking yet compelling secret among them. But be ware, your decision will change their lives, forever.\n\nThis is a prototype, aims for laying foundations and systems, storytelling and other elements are not refined yet. A lot of bugs might also exists so there is a very high possibility your save would not be able to transfer to future build.\n\n==========================================================================================================\n\nCredit:\n\nCode/Art/Script: f1shsticker\n\nTranslation:\n\nFont: Adobe Garamond Pro\n\n"
    new "\n\nOutland Wanderer est un Visual Novel RPG crée par f1shsticker.\n\nLe joueur joue un homme iconnu, étranger et perdu (outsider en anglais) qui atteri sur le continent de Mokken. Dans sa tentative de retourner dans sa propre tribu, il se lie d'amitié et noue des relations avec les habitants, s'attaque à des forces inconnues et découvre un secret choquant et fascinant parmi eux. Mais attention, vos décisions changeront leur vie pour toujours.\n\nCeci est un prototype, visant à jeter les bases et les systèmes de fonctionnement du jeu, la narration et d'autres éléments sont sujets à des changements. De nombreux bogues peuvent également exister, il est donc très probable que votre sauvegarde ne puisse pas être transférée vers une version utltérieure.\n\nNote du traducteur de la version française: Salut! C'est SannomPL, si vous remarquez des erreurs ou des recommandations pour améliorer la narration française du jeu, n'hésitez pas à me contacter! Merci. <3 \n\n == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==\n\nCrédits: \n\nCode/Art/Script: f1shsticker\n\nTraduction française: SannomPL\n\nFont: Adobe Garamond Pro\n\n"



translate french strings:


    old "\n\nOutland Wanderer is a Visual Novel RPG created by f1shsticker.\n\nPlayer plays an outsider stumbling upon the continent of Mokken. In his attempt to travel back to his own Tribe, he bonds and form different relationship with the locals, tackles on unknown forces, and discover shocking yet compelling secret among them. But be ware, your decision will change their lives, forever.\n\nThis is a prototype, aims for laying foundations and systems, storytelling and other elements are not refined yet. A lot of bugs might also exists so there is a very high possibility your save would not be able to transfer to future build.\n\n==========================================================================================================\n\nCredit:\n\nCode/Art/Script: f1shsticker\n\nTranslation: French: Sannom\n\nFont: Adobe Garamond Pro\n\n"
    new "\n\nOutland Wanderer est un Visual Novel RPG crée par f1shsticker.\n\nLe joueur joue un homme iconnu, étranger et perdu (outsider en anglais) qui atteri sur le continent de Mokken. Dans sa tentative de retourner dans sa propre tribu, il se lie d'amitié et noue des relations avec les habitants, s'attaque à des forces inconnues et découvre un secret choquant et fascinant parmi eux. Mais attention, vos décisions changeront leur vie pour toujours.\n\nCeci est un prototype, visant à jeter les bases et les systèmes de fonctionnement du jeu, la narration et d'autres éléments sont sujets à des changements. De nombreux bogues peuvent également exister, il est donc très probable que votre sauvegarde ne puisse pas être transférée vers une version utltérieure.\n\nNote du traducteur de la version française: Salut! C'est SannomPL, si vous remarquez des erreurs ou des recommandations pour améliorer la narration française du jeu, n'hésitez pas à me contacter! Merci. <3 \n\n == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==\n\nCrédits: \n\nCode/Art/Script: f1shsticker\n\nTraduction:\n\nFrançais: SannomPL\n\nFont: Adobe Garamond Pro\n\n"



translate french strings:


    old "\n\nOutland Wanderer is a Visual Novel RPG created by f1shsticker.\n\nPlayer plays an outsider stumbling upon the continent of Mokken. In his attempt to travel back to his own Tribe, he bonds and form different relationship with the locals, tackles on unknown forces, and discover shocking yet compelling secret among them. But be ware, your decision will change their lives, forever.\n\nThis is a prototype, aims for laying foundations and systems, storytelling and other elements are not refined yet. A lot of bugs might also exists so there is a very high possibility your save would not be able to transfer to future build.\n\n==========================================================================================================\n\n{a=https://discord.gg/QnbJMGhZhV}Official Discord Server{/a}\n\nCredit:\n\nCode/Art/Script:   f1shsticker {a=https://twitter.com/OutlandWanderer}Twitter{/a}\n\nScript: Nyarlothotep {a=https://twitter.com/LoveCountry45}Twitter{/a}\n\nMusic:   Pinewood Jerry  {a=https://twitter.com/Pinewood_Jerry}Twitter{/a}\n\nFrench Translation:  Sannom(Paul)  {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nPortuguese Translation:  Fábio.T\n\nFont: Adobe Garamond Pro\n\n"
    new "\n\nOutland Wanderer est un Visual Novel RPG crée par f1shsticker.\n\nLe joueur joue un homme étranger qui atteri sur le continent de Mokken. En tentant de retourner dans sa propre tribu, il se lie d'amitié et noue des relations avec les habitants, s'attaque à des forces inconnues et découvre des secrets choquants et fascinants parmi eux. Mais attention, vos décisions changeront leur vie pour toujours.\n\nCeci est un prototype, visant à montrer les bases et les systèmes de fonctionnement du jeu. La narration et d'autres éléments sont sujets à des changements. De nombreux bogues peuvent également exister, il est donc très probable que votre sauvegarde ne puisse pas être transférée vers une version utltérieure.\n\nNote du traducteur de la version française: Salut! C'est SannomPL, si vous remarquez des erreurs ou des recommandations pour améliorer la narration française du jeu, n'hésitez pas à me contacter! Merci. <3 \n\n == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==\n\n{a=https://discord.gg/QnbJMGhZhV}Serveur Discord Officiel{/a}\n\nCrédits: \n\nCode/Art/Script: f1shsticker {a=https://twitter.com/OutlandWanderer}Twitter{/a}\n\nScript: Nyarlothotep {a=https://twitter.com/LoveCountry45}Twitter{/a}\n\nMusique: Pinewood Jerry  {a=https://twitter.com/Pinewood_Jerry}Twitter{/a}\n\nTraduction:\n\nFrançais: SannomPL {a=https://twitter.com/SannomTigris}Twitter{/a}\nrelecture par Kitsuka\n\nPortugais: Fábio.T\n\nFont: Adobe Garamond Pro\n\n"



translate french strings:


    old "\n\nOutland Wanderer is a Visual Novel RPG created by f1shsticker.\n\nPlayer plays an outsider stumbling upon the continent of Mokken. In his attempt to travel back to his own Tribe, he bonds and form different relationship with the locals, tackles on unknown forces, and discover shocking yet compelling secret among them. But be ware, your decision will change their lives, forever.\n\nThis is a prototype, aims for laying foundations and systems, storytelling and other elements are not refined yet. A lot of bugs might also exists so there is a very high possibility your save would not be able to transfer to future build.\n\n==========================================================================================================\n\n{a=https://discord.gg/QnbJMGhZhV}Official Discord Server{/a}\n\nCredit:\n\nCode/Art/Script:   f1shsticker {a=https://twitter.com/OutlandWanderer}Twitter{/a}\n\nScript: Nyarlothotep {a=https://twitter.com/LoveCountry45}Twitter{/a} {p}\n\nLonelyTree {a=https://discordapp.com/users/273928084388839425}Discord{/a}\n\nMusic:   Pinewood Jerry  {a=https://twitter.com/Pinewood_Jerry}Twitter{/a}\n\nFrench Translation:  Sannom(Paul)  {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nPortuguese Translation:  Fábio.T  {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nFont: Adobe Garamond Pro\n\n"
    new ""



translate french strings:


    old "\n\nOutland Wanderer is a Visual Novel RPG created by f1shsticker.\n\nPlayer plays an outsider stumbling upon the continent of Mokken. In his attempt to travel back to his own Tribe, he bonds and form different relationship with the locals, tackles on unknown forces, and discover shocking yet compelling secret among them. But be ware, your decision will change their lives, forever.\n\nThis is a prototype, aims for laying foundations and systems, storytelling and other elements are not refined yet. A lot of bugs might also exists so there is a very high possibility your save would not be able to transfer to future build.\n\n==========================================================================================================\n\n{a=https://discord.gg/QnbJMGhZhV}Official Discord Server{/a}\n\nCredit:\n\nCode/Art/Script:   f1shsticker {a=https://twitter.com/OutlandWanderer}Twitter{/a}\n\nScript: Nyarlothotep {a=https://twitter.com/LoveCountry45}Twitter{/a} {p}\n\nLonelyTree {a=https://discordapp.com/users/273928084388839425}Discord{/a}\n\nMagnolia\n\nMusic:  Will o Wisp  {a=https://soundcloud.com/willowispproductions}Twitter{/a}\n\nPinewood Jerry  {a=https://twitter.com/Pinewood_Jerry}Twitter{/a}\n\nFrench Translation:  Sannom(Paul)  {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nPortuguese Translation:  Fábio.T  {a=https://twitter.com/SannomTigris}Twitter{/a}\n\nFont: Adobe Garamond Pro\n\n"
    new ""
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
